# Docs về code flow của acmsolver

## I. Giải thích về chức năng của các file

### 1.1 acm_solver
Chứa source code của service solver.
### 1.2 generated/
Chứa các file được sinh ra từ grpc 
### 1.3 orm/
Odm.py: thực chất là chứa các model của mongo trong service solver
### 1.4 server/
Chứa file server grpc python, định nghĩa các rpc, là đầu vào để client tương tác với server.
### 1.5 config.py/
Chứa các thông số config
### 1.6 utils.py
Chứa các hàm utilities
### 1.7 solver/
Thư mục chính chứa code  để giải bài toán solver. Hầu hết các hàm đã được viết docstring khá dễ hiểu.<br>
`exceptions_handler.py`: module chính để xử lí lỗi, chứa các mã lỗi custom và code để check lỗi, exception.<br>
`model_ready_data_converter.py`: Chuyển dữ liệu từ dạng processed_data thành model_ready_data.<br>
model_ready_data là 1 dictionary, sẵn sàng để cho vào hàm `_solve_b_c()` để giải bài toán tối ưu bằng CPLEX.<br>
`preprocess.py`: module chính để convert raw_data (dữ liệu vừa lấy từ db ra) trở thành processed_data.<br>
Process_data là dữ liệu đã đc xử lí từ raw_data để sẵn sàng chuyển thành model_ready_data.<br>
Process_data chứa 2 DataFrame là processed_data.places và process_data.campaigns.<br>
`splitter.py`: module phân chia dữ liệu ra các bài toán con.<br>
`model_solver.py`: Module chính để giải bài toán solver.

## II. Flow khi gọi rpc solve

rpc solve khi đc gọi sẽ gọi hàm solve_prob trong model_solver.py.

Trước hết, chạy cell dưới đây để import các thứ cần thiết

In [2]:
import sys
sys.path.append('../acm_solver/')
sys.path.append('../acm_solver/orm/')
sys.path.append('../acm_solver/solver/')
sys.path.append('../acm_solver/generated')

#database 
import odm
import mongoengine as me

#local modules
import exceptions_handler
import utils
import reverse_convert
import splitter
import model_ready_data_converter
import solver_helpers
from solver_helpers import (RawData,
                            SubProblemRawData, 
                            PreprocessedData, 
                            PartitionedData, 
                            Mapper, 
                            ProcessClassA, 
                            CampaignProfile ,
                            Alpha, 
                            get_num_subproblems,
                            PlaceProfile)
from preprocess import PreprocessConverter
import config as cfg
import config 
from model_solver import _solve_b_c

#others
import datetime
import pandas as pd
import numpy as np
from docplex.mp.model import Model
import math
import time
import logging
import acm_base_pb2
logging.basicConfig(level= logging.DEBUG)

Chạy cell bên dưới để đặt các config

In [3]:
dev_str  = "mongodb://acm:AWing%402020@118.70.206.204:27017/?authSource=admin"
staging_str = "mongodb://172.16.2.106:27017"
demo_str = "mongodb://192.168.10.202:27017"

cfg.connection_str = dev_str
me.disconnect()
me.connect(db ="acmSolver",host = cfg.connection_str, tz_aware = True)

problem_id = "60d1a81f16b3330442537211"
# config = cfg
full_tik = time.time()
adjust_start_date = False
split_method = "by_places"

### 2.1 Giải thích code chính bên trong `solve_prob(...)`

Cell bên dưới lấy dữ liệu từ mongodb

In [4]:
raw_data, lower_ratio = solver_helpers.query_raw_data(problem_id)

có 3 dạng dữ liệu được dùng trong solver đó là `raw_data`, `preprocessed_data` và `model_ready_data`.<br>
raw_data là dữ liệu thô lấy từ database, chưa có chỉnh sửa gì.<br>
Có thể chạy cell bến dưới, thay lần lượt bằng `raw_data.places` (list), `raw_data.campaigns`(list), `lower_ratio`(int) để hiểu hơn kiểu dữ liệu tương ứng.

In [5]:
raw_data.campaigns

[{'_id': ObjectId('60d1a82016b3330442537212'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '4768939651732014836_1',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'BANNER_STATIC',
  'total': 103632.91,
  'placeIds': [4979871131880682040,
   5181053909251379448,
   4857469430519615278,
   5577578545256809161,
   5538742900884010760,
   100],
  'weights': [],
  'profiles': [[{'values': [0], 'type': 'GENDER'},
    {'type': 'AGE', 'values': [0, 1, 2]}]],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 991000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b3330442537213'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '4768939651732014836_2',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'BANNER_STATIC',
  'total': 2589743.5,
  'placeIds': [5181053909251379448],
  'weights': [],
  'profiles': [[{'values': [0], 'type': 'GENDER'},
    {'type': 'AGE', 'values': [0, 1, 2]}]],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 992000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b3330442537214'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '4810238136557669178_1',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'BANNER_STATIC',
  'total': 103632.91,
  'placeIds': [4979871131880682040,
   5181053909251379448,
   4857469430519615278,
   5577578545256809161,
   5538742900884010760,
   100],
  'weights': [],
  'profiles': [[{'values': [1], 'type': 'GENDER'},
    {'type': 'AGE', 'values': [0]}]],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 992000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b3330442537215'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '4810238136557669178_2',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'BANNER_STATIC',
  'total': 2589743.5,
  'placeIds': [5181053909251379448],
  'weights': [],
  'profiles': [[{'values': [1], 'type': 'GENDER'},
    {'type': 'AGE', 'values': [0]}]],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 992000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b3330442537216'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '5247609002361599862_1',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'BANNER_STATIC',
  'total': 103632.91,
  'placeIds': [4979871131880682040,
   5181053909251379448,
   4857469430519615278,
   5577578545256809161,
   5538742900884010760,
   100],
  'weights': [],
  'profiles': [[{'values': [1], 'type': 'GENDER'},
    {'type': 'AGE', 'values': [2, 3, 4]}]],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 993000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b3330442537217'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '5247609002361599862_2',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'BANNER_STATIC',
  'total': 2589743.5,
  'placeIds': [5181053909251379448],
  'weights': [],
  'profiles': [[{'values': [1], 'type': 'GENDER'},
    {'type': 'AGE', 'values': [2, 3, 4]}]],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 993000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b3330442537218'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '5275363820481263653_1',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'BANNER_STATIC',
  'total': 103632.91,
  'placeIds': [4979871131880682040,
   5181053909251379448,
   4857469430519615278,
   5577578545256809161,
   5538742900884010760,
   100],
  'weights': [],
  'profiles': [[{'values': [0], 'type': 'GENDER'},
    {'type': 'AGE', 'values': [1, 3, 5]}]],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 993000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b3330442537219'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '5275363820481263653_2',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'BANNER_STATIC',
  'total': 2589743.5,
  'placeIds': [5181053909251379448],
  'weights': [],
  'profiles': [[{'values': [0], 'type': 'GENDER'},
    {'type': 'AGE', 'values': [1, 3, 5]}]],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 994000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b333044253721a'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '5322575190744422716_1',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'BANNER_STATIC',
  'total': 166924.75,
  'placeIds': [4979871131880682040,
   5181053909251379448,
   4857469430519615278,
   5577578545256809161,
   5538742900884010760,
   100],
  'weights': [{'date': '2021-02-01T17:00:00Z', 'value': 20.0}],
  'profiles': [],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 994000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b333044253721b'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '5322575190744422716_2',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'BANNER_STATIC',
  'total': 19235.0,
  'placeIds': [5181053909251379448],
  'weights': [{'date': '2021-02-01T17:00:00Z', 'value': 20.0}],
  'profiles': [],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 994000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b333044253721c'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '5370791925364426073_1',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'BANNER_STATIC',
  'total': 103632.91,
  'placeIds': [4979871131880682040,
   5181053909251379448,
   4857469430519615278,
   5577578545256809161,
   5538742900884010760,
   100],
  'weights': [{'date': '2021-02-01T17:00:00Z', 'value': 20.0}],
  'profiles': [],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 995000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b333044253721d'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '5370791925364426073_2',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'BANNER_STATIC',
  'total': 2589743.5,
  'placeIds': [5181053909251379448],
  'weights': [{'date': '2021-02-01T17:00:00Z', 'value': 20.0}],
  'profiles': [],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 995000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b333044253721e'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '5387657435205013825_1',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'BANNER_STATIC',
  'total': 103632.91,
  'placeIds': [4979871131880682040,
   5181053909251379448,
   4857469430519615278,
   5577578545256809161,
   5538742900884010760,
   100],
  'weights': [],
  'profiles': [[{'values': [0], 'type': 'GENDER'},
    {'type': 'AGE', 'values': [4, 5, 6]}]],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 995000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b333044253721f'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '5387657435205013825_2',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'BANNER_STATIC',
  'total': 2589743.5,
  'placeIds': [5181053909251379448],
  'weights': [],
  'profiles': [[{'values': [0], 'type': 'GENDER'},
    {'type': 'AGE', 'values': [4, 5, 6]}]],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 996000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b3330442537220'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '5400965728863573515_1',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'BANNER_STATIC',
  'total': 103632.91,
  'placeIds': [4979871131880682040,
   5181053909251379448,
   4857469430519615278,
   5577578545256809161,
   5538742900884010760,
   100],
  'weights': [],
  'profiles': [[{'values': [1], 'type': 'GENDER'},
    {'type': 'AGE', 'values': [0, 1, 2, 3, 4, 5, 6]}]],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 996000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b3330442537221'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '5400965728863573515_2',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'BANNER_STATIC',
  'total': 2589743.5,
  'placeIds': [5181053909251379448],
  'weights': [],
  'profiles': [[{'values': [1], 'type': 'GENDER'},
    {'type': 'AGE', 'values': [0, 1, 2, 3, 4, 5, 6]}]],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 996000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b3330442537222'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '5438574239652778058_1',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_A',
  'type': 'BANNER_STATIC',
  'total': 103632.91,
  'placeIds': [4979871131880682040,
   5181053909251379448,
   4857469430519615278,
   5577578545256809161,
   5538742900884010760,
   100],
  'weights': [{'date': '2021-02-01T17:00:00Z', 'value': 20.0}],
  'profiles': [],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 996000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b3330442537223'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '5438574239652778058_2',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_A',
  'type': 'BANNER_STATIC',
  'total': 2589743.5,
  'placeIds': [5181053909251379448],
  'weights': [{'date': '2021-02-01T17:00:00Z', 'value': 20.0}],
  'profiles': [],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 997000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b3330442537224'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '5577398347147938092_1',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'BANNER_STATIC',
  'total': 103632.91,
  'placeIds': [4979871131880682040,
   5181053909251379448,
   4857469430519615278,
   5577578545256809161,
   5538742900884010760,
   100],
  'weights': [],
  'profiles': [[{'values': [1], 'type': 'GENDER'},
    {'type': 'AGE', 'values': [0, 3, 6]}]],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 997000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b3330442537225'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '5577398347147938092_2',
  'isNetwork': True,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'BANNER_STATIC',
  'total': 2589743.5,
  'placeIds': [5181053909251379448],
  'weights': [],
  'profiles': [[{'values': [1], 'type': 'GENDER'},
    {'type': 'AGE', 'values': [0, 3, 6]}]],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 997000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b3330442537226'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '4638036435127515710_0',
  'isNetwork': False,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 8, 26, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_A',
  'type': 'DEFAULT',
  'total': 4120000.0,
  'placeIds': [4857469430519615278],
  'weights': [],
  'profiles': [],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 998000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b3330442537227'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '4650504253994331355_0',
  'isNetwork': False,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 8, 26, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'DEFAULT',
  'total': 2589239.0,
  'placeIds': [4857469430519615278],
  'weights': [],
  'profiles': [],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 998000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b3330442537228'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '4713760987931352697_0',
  'isNetwork': False,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 8, 26, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'DEFAULT',
  'total': 4240000.0,
  'placeIds': [5023173597424371233],
  'weights': [],
  'profiles': [],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 998000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b3330442537229'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '4718198705721931407_0',
  'isNetwork': False,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'DEFAULT',
  'total': 3660171.0,
  'placeIds': [5023173597424371233],
  'weights': [],
  'profiles': [[{'values': [0], 'type': 'GENDER'},
    {'type': 'AGE', 'values': [1, 3, 5]}]],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 39, 999000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b333044253722a'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '4741325520555630568_0',
  'isNetwork': False,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'DEFAULT',
  'total': 3608376.0,
  'placeIds': [5538742900884010760],
  'weights': [],
  'profiles': [[{'values': [1], 'type': 'GENDER'},
    {'type': 'AGE', 'values': [0, 1, 2, 3, 4, 5, 6]}]],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 40, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},
 {'_id': ObjectId('60d1a82016b333044253722b'),
  'problemId': '60d1a81f16b3330442537211',
  'campaignId': '4796633772157943273_0',
  'isNetwork': False,
  'startDate': datetime.datetime(2021, 6, 21, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'expiredDate': datetime.datetime(2021, 9, 29, 17, 0, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>),
  'priority': 'CLASS_B',
  'type': 'DEFAULT',
  'total': 3608376.0,
  'placeIds': [5538742900884010760],
  'weights': [],
  'profiles': [[{'values': [0], 'type': 'GENDER'},
    {'type': 'AGE', 'values': [0, 1, 2]}]],
  'createDate': datetime.datetime(2021, 6, 22, 9, 6, 40, 1000, tzinfo=<bson.tz_util.FixedOffset object at 0x000001F115D1F388>)},

Ở bước dưới đây, dữ liệu raw sẽ được "làm đúng" bao gồm:<br>
Chuyển dữ liệu thời gian về local time,<br>
Loại bỏ những campaign ko chạy ở đâu,<br>
Loại bỏ những campaign class B có lượng chạy = 0,<br>
`adjust_start_date = True`: Nếu ngày bắt đầu của campaign < ngày hôm nay, chuyển ngày bắt đầu về ngày hôm nay,<br>
Khi chạy bình thường, `adjust_start_date` sẽ là `True`. Nhưng khi debug, có thể để nó là `False`.<br>
Loại bỏ những campaign có start date > end date.<br>

In [6]:
raw_data = utils.CorrectRawData.correct(raw_data, adjust_start_date)

Cell dưới check và báo lỗi, có thể xem chi tiết về các lỗi ở module `exceptions_handler.py`<br>
`check_invalid_share_type(raw_places, problem_id)`<br>
`check_no_campaign(raw_campaigns, problem_id)`<br>
`check_no_place(raw_places, problem_id)`<br>
`check_invalid_campaign(raw_campaigns, problem_id)`<br>
`check_invalid_place(raw_places, problem_id)`<br>
`check_valid_number_class_c(raw_campaigns, True)`<br>
`check_valid_number_class_c(raw_campaigns, False)`

In [7]:
exceptions_handler.validate_input(raw_data, problem_id)

Ở cell dưới, việc phải `try` để lấy `problem_type` do trong quá trình debug, dữ liệu test trong db có thể ko có problem_id

In [8]:
# Check problem type 
problem_type = 'NETWORK_PROBLEM'
try:
    problem_type  = odm.ASProblemInfo.objects(id = problem_id).as_pymongo()[0]['problemType']
except:
    logging.info("Không có problem info, có thể đang sử dụng dữ liệu test.")
    pass
logging.info(f"Problem type:{problem_type}")

if problem_type == "STANDALONE_PROBLEM":
    raw_data = solver_helpers.process_standalone_problem(raw_data)
    # Kiểm tra sau khi xử lí bài toán standalone có còn campaign nào không
    exceptions_handler.check_no_campaign(raw_data.campaigns, problem_id) 

# Nếu không có dữ liệu campaign type B,C thêm 1 campaign giả type B với total ~ 0
if utils.no_type_b_or_c(raw_data.campaigns) == True:  
    raw_data.campaigns.append(utils.create_temp_campaign(problem_id, raw_data))

INFO:root:Problem type:NETWORK_PROBLEM

In [9]:
num_subproblems = get_num_subproblems(raw_data, config)
all_subproblems_data = splitter.split(num_subproblems, raw_data, split_method)
logging.info(f"Splitted into {str(num_subproblems)} problem(s)!")

INFO:root:problem size: approx 471064
INFO:root:subproblem max size:1000000
INFO:root:Splitting into 1 problem(s)!

Split by places.

INFO:root:Splitted into 1 problem(s)!

Sau khi chia ra các bài toán con, hàm `solve_multiprocess` hoặc `solve_single_process` sẽ được gọi, về cơ bản hai hàm này sẽ gọi `solve_sub_prob`. Đây là hàm chính để giải từng bài toán con, sẽ được giải thích ở dưới.

### 2.2. Giải thích code chính bên trong `solve_sub_prob(...)`

Chạy cell bên dưới để gán giá trị cho subproblem_data, subproblem_data là raw_data, nhưng đã được chia nhỏ đi.

In [10]:
subproblem_data = all_subproblems_data[0]

In [11]:
problem_id = subproblem_data.campaigns[0]['problemId']  # Get problem_id
# If there is no campaign type B or C, add a fake campaign B with total approx 0
if utils.no_type_b_or_c(subproblem_data.campaigns) == True:
    subproblem_data.campaigns.append(utils.create_temp_campaign(problem_id,subproblem_data))

tik = time.time()
# Preprocess and get model-ready data
preprocessed_data, mapper = PreprocessConverter.convert_from_raw_data(subproblem_data)
model_ready_data = model_ready_data_converter.convert_from_processed_data(preprocessed_data)

`preprocessed_data` là các DataFrame của places, campaigns đã được xử lí, mapping sang dạng khác như int để dễ xử lí.<br>
`model_ready_data`(dict) là dữ liệu sẵn sàng ném vào `_solve_b_c()` để giải bằng CPLEX.<br>
Có thể chạy cell bến dưới, thay lần lượt bằng `preprocessed_data.campaigns, preprocessed_data.places, mapper.campaigns_mapper, mapper.date_int_mapper, mapper.places_mapper, model_ready_data` để hiểu hơn kiểu dữ liệu tương ứng.

In [12]:
preprocessed_data.campaigns

,problemId,original_id,isNetwork,priority,type,total,place_ids,weights,profiles,createDate,solve_id,dates,solve_place_ids
0,60d1a81f16b3330442537211,4768939651732014836_1,True,CLASS_B,1,1.036329e+05,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.991000+00:00,0,"[0, 100]","[66, 67, 77, 78, 11, 12, 44, 45, 22, 23, 33, 34]"
1,60d1a81f16b3330442537211,4768939651732014836_2,True,CLASS_B,1,2.589743e+06,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.992000+00:00,1,"[0, 100]","[77, 78]"
2,60d1a81f16b3330442537211,4810238136557669178_1,True,CLASS_B,1,1.036329e+05,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.992000+00:00,2,"[0, 100]","[68, 79, 13, 46, 24, 35]"
3,60d1a81f16b3330442537211,4810238136557669178_2,True,CLASS_B,1,2.589743e+06,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.992000+00:00,3,"[0, 100]",[79]
4,60d1a81f16b3330442537211,5247609002361599862_1,True,CLASS_B,1,1.036329e+05,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.993000+00:00,4,"[0, 100]","[69, 70, 80, 81, 14, 15, 47, 48, 25, 26, 36, 37]"
5,60d1a81f16b3330442537211,5247609002361599862_2,True,CLASS_B,1,2.589743e+06,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.993000+00:00,5,"[0, 100]","[80, 81]"
6,60d1a81f16b3330442537211,5275363820481263653_1,True,CLASS_B,1,1.036329e+05,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.993000+00:00,6,"[0, 100]","[66, 71, 72, 77, 82, 83, 11, 16, 17, 44, 49, 5..."
7,60d1a81f16b3330442537211,5275363820481263653_2,True,CLASS_B,1,2.589743e+06,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.994000+00:00,7,"[0, 100]","[77, 82, 83]"
8,60d1a81f16b3330442537211,5322575190744422716_1,True,CLASS_B,1,1.669247e+05,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.994000+00:00,8,"[0, 100]","[66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 7..."
9,60d1a81f16b3330442537211,5322575190744422716_2,True,CLASS_B,1,1.923500e+04,[5181053909251379448],{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.994000+00:00,9,"[0, 100]","[77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87]"
10,60d1a81f16b3330442537211,5370791925364426073_1,True,CLASS_B,1,1.036329e+05,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.995000+00:00,10,"[0, 100]","[66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 7..."
11,60d1a81f16b3330442537211,5370791925364426073_2,True,CLASS_B,1,2.589743e+06,[5181053909251379448],{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.995000+00:00,11,"[0, 100]","[77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87]"
12,60d1a81f16b3330442537211,5387657435205013825_1,True,CLASS_B,1,1.036329e+05,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.995000+00:00,12,"[0, 100]","[71, 73, 82, 84, 16, 18, 49, 51, 27, 29, 38, 40]"
13,60d1a81f16b3330442537211,5387657435205013825_2,True,CLASS_B,1,2.589743e+06,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,13,"[0, 100]","[82, 84]"
14,60d1a81f16b3330442537211,5400965728863573515_1,True,CLASS_B,1,1.036329e+05,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,14,"[0, 100]","[68, 69, 70, 74, 75, 79, 80, 81, 85, 86, 13, 1..."
15,60d1a81f16b3330442537211,5400965728863573515_2,True,CLASS_B,1,2.589743e+06,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,15,"[0, 100]","[79, 80, 81, 85, 86]"
16,60d1a81f16b3330442537211,5577398347147938092_1,True,CLASS_B,1,1.036329e+05,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.997000+00:00,16,"[0, 100]","[68, 69, 74, 79, 80, 85, 13, 14, 19, 46, 47, 5..."
17,60d1a81f16b3330442537211,5577398347147938092_2,True,CLASS_B,1,2.589743e+06,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.997000+00:00,17,"[0, 100]","[79, 80, 85]"
18,60d1a81f16b3330442537211,4650504253994331355_0,False,CLASS_B,0,2.589239e+06,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.998000+00:00,18,"[0, 66]","[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]"
19,60d1a81f16b3330442537211,4713760987931352697_0,False,CLASS_B,0,4.240000e+06,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.998000+00:00,19,"[0, 66]","[55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]"
20,60d1a81f16b3330442537211,4718198705721931407_0,False,CLASS_B,0,3.660171e+06,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.999000+00:00,20,"[0, 100]","[55, 60, 61]"
21,60d1a81f16b3330442537211,4741325520555630568_0,False,CLASS_B,0,3.608376e+06,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40+00:00,21,"[0, 100]","[24, 25, 26, 30, 31]"
22,60d1a81f16b3330442537211,4796633772157943273_0,False,CLASS_B,0,3.608376e+06,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.001000+00:00,22,"[0, 100]","[22, 23]"
23,60d1a81f16b3330442537211,4823653667180754890_0,False,CLASS_B,0,1.229684e+06,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.001000+00:00,23,"[0, 66]","[22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]"
24,60d1a81f16b3330442537211,4824859557802329616_0,False,CLASS_B,0,3.556581e+06,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.002000+00:00,24,"[0, 100]","[11, 16, 17]"
25,60d1a81f16b3330442537211,4904151939315150524_0,False,CLASS_B,0,3.556581e+06,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.002000+00:00,25,"[0, 100]","[13, 14, 19]"
26,60d1a81f16b3330442537211,4987628296907052401_0,False,CLASS_B,0,3.660171e+06,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.003000+00:00,26,"[0, 100]","[55, 56]"
27,60d1a81f16b3330442537211,5004060173322688003_0,False,CLASS_B,0,3.660171e+06,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.003000+00:00,27,"[0, 100]",[57]
28,60d1a81f16b3330442537211,5005141348821177586_0,False,CLASS_B,0,3.608376e+06,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.004000+00:00,28,"[0, 100]","[22, 27, 28]"
29,60d1a81f16b3330442537211,5008562159266208975_0,False,CLASS_B,0,3.556581e+06,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.004000+00:00,29,"[0, 100]","[16, 18]"
30,60d1a81f16b3330442537211,5112510634931261580_0,False,CLASS_B,0,3.556581e+06,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.005000+00:00,30,"[0, 100]","[13, 14, 15, 19, 20]"
31,60d1a81f16b3330442537211,5116176280026807920_0,False,CLASS_B,0,3.556581e+06,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.005000+00:00,31,"[0, 100]",[13]
32,60d1a81f16b3330442537211,5140955443670820219_0,False,CLASS_B,0,3.608376e+06,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.005000+00:00,32,"[0, 100]","[25, 26]"
33,60d1a81f16b3330442537211,5144070500760291817_0,False,CLASS_B,0,3.660171e+06,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.006000+00:00,33,"[0, 100]","[58, 59]"
34,60d1a81f16b3330442537211,5145360317263062170_0,False,CLASS_B,0,1.635884e+05,[4827998237552142792],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.006000+00:00,34,"[0, 66]","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]"
35,60d1a81f16b3330442537211,5261690011954745524_0,False,CLASS_B,0,3.660171e+06,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.007000+00:00,35,"[0, 100]","[57, 58, 59, 63, 64]"
36,60d1a81f16b3330442537211,5326884055688590955_0,False,CLASS_B,0,1.118869e+06,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.007000+00:00,36,"[0, 66]","[55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]"
37,60d1a81f16b3330442537211,5349652368050952557_0,False,CLASS_B,0,4.120000e+06,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.008000+00:00,37,"[0, 66]","[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]"
38,60d1a81f16b3330442537211,5351581853241914431_0,False,CLASS_B,0,3.556581e+06,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.008000+00:00,38,"[0, 100]","[14, 15]"
39,60d1a81f16b3330442537211,5430288141589897773_0,False,CLASS_B,0,3.608376e+06,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.008000+00:00,39,"[0, 100]","[24, 25, 30]"
40,60d1a81f16b3330442537211,5447298725065630394_0,False,CLASS_B,0,3.660171e+06,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.009000+00:00,40,"[0, 100]","[57, 58, 63]"
41,60d1a81f16b3330442537211,5471706532034127453_0,False,CLASS_B,0,4.180000e+06,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.009000+00:00,41,"[0, 66]","[22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]"
42,60d1a81f16b3330442537211,5596899021949443719_0,False,CLASS_B,0,1.400000e+05,[4827998237552142792],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.010000+00:00,42,"[0, 66]","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]"
43,60d1a81f16b3330442537211,5609987844990570937_0,False,CLASS_B,0,3.660171e+06,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.010000+00:00,43,"[0, 100]","[60, 62]"
44,60d1a81f16b3330442537211,5646870611503620553_0,False,CLASS_B,0,3.608376e+06,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.011000+00:00,44,"[0, 100]",[24]
45,60d1a81f16b3330442537211,5678313728368360859_0,False,CLASS_B,0,3.608376e+06,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.011000+00:00,45,"[0, 100]","[27, 29]"
46,60d1a81f16b3330442537211,5740071104871774323_0,False,CLASS_B,0,3.556581e+06,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.012000+00:00,46,"[0, 100]","[11, 12]"
47,60d1a81f16b3330442537211,5438574239652778058_1,True,CLASS_A,1,1.036329e+05,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,47,"[0, 100]","[66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 7..."
48,60d1a81f16b3330442537211,5438574239652778058_2,True,CLASS_A,1,2.589743e+06,[5181053909251379448],{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.997000+00:00,48,"[0, 100]","[77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87]"
49,60d1a81f16b3330442537211,4638036435127515710_0,False,CLASS_A,0,4.120000e+06,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.998000+00:00,49,"[0, 66]","[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]"
50,60d1a81f16b3330442537211,4818379653085429819_0,False,CLASS_A,0,1.400000e+05,[4827998237552142792],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.001000+00:00,50,"[0, 66]","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]"
51,60d1a81f16b3330442537211,4943071185361192679_0,False,CLASS_A,0,4.240000e+06,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.002000+00:00,51,"[0, 66]","[55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]"
52,60d1a81f16b3330442537211,5152950634416065152_0,False,CLASS_A,0,4.180000e+06,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.007000+00:00,52,"[0, 66]","[22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]"

In [13]:
solve_details = _solve_b_c(model_ready_data,  
                          alpha_formula = '2',
                          p = lower_ratio, 
                          export_model = False,
                          evenness_priority = 1)  # Solve B,C bằng CPLEX

DEBUG:root:constraints (1) added!
DEBUG:root:constraints (2) added!
DEBUG:root:constraints (3) added!
DEBUG:root:constraints (4) added!
DEBUG:root:constraints (5) added!
DEBUG:root:Trade off optimization function
DEBUG:root:obj.function added!

Đến đây thì cơ bản đã giải xong, các bước còn lại như giải A, mapping ngược lại, insert vào db

## III. PreprocessConverter

Mục đích chính của `PreprocessConverter` là chuyển dữ liệu từ dạng `raw_data` về `preprocessed_data`.

preprocessed_data chứa 2 pandas.DataFrame (1 cái cho campaign, 1 cái cho place), mục đích của nó là chứa các dữ liệu đã được "xử lí": như chuyển id của campaign về dạng int, chuyển ngày tháng về int, convert profiles sang các nhóm profile,...<br>
Dữ liệu biến đổi nhiều nhất ở bước này. <br>
Hàm được gọi từ solver là `PreprocessConverter.convert_from_raw_data()`<br>
Gồm 3 bước :<br>
* Tạo 1 mapper từ kiểu datetime sang int
* Preprocess places
* Preprocess campaigns

Dưới đây sẽ mô tả chi tiết các bước

### 3.1. Tạo mapper từ datetime sang int

Trong hàm `convert_from_raw_data()`:

In [14]:
raw_campaigns = raw_data.campaigns
raw_places = raw_data.places

In [15]:
preprocessed_data = PreprocessedData()
mapper = Mapper()

In [16]:
problem_start_date = min(pd.DataFrame(raw_campaigns)['startDate'])
date_int_mapper = PreprocessConverter._map_datetime_to_int(problem_start_date, cfg)
mapper.date_int_mapper = date_int_mapper
total_running_days = PreprocessConverter._get_running_days(pd.DataFrame(raw_campaigns))

mapper thứ nhất, `date_int_mapper` được tạo ra tại bước trên, như tên gọi thì mục đích của `date_int_mapper` là ánh xạ ngày và index tương ứng trong solver. Nó là 1 dictionary gồm 2 nhỏ hơn: `date_to_int` và `int_to_dict`. Có thể chạy cell bên đươi để hiểu rõ hơn.

In [17]:
date_int_mapper['date_to_int']

{Timestamp('2020-06-22 00:00:00+0700', tz='SE Asia Standard Time'): -365,
 Timestamp('2020-06-23 00:00:00+0700', tz='SE Asia Standard Time'): -364,
 Timestamp('2020-06-24 00:00:00+0700', tz='SE Asia Standard Time'): -363,
 Timestamp('2020-06-25 00:00:00+0700', tz='SE Asia Standard Time'): -362,
 Timestamp('2020-06-26 00:00:00+0700', tz='SE Asia Standard Time'): -361,
 Timestamp('2020-06-27 00:00:00+0700', tz='SE Asia Standard Time'): -360,
 Timestamp('2020-06-28 00:00:00+0700', tz='SE Asia Standard Time'): -359,
 Timestamp('2020-06-29 00:00:00+0700', tz='SE Asia Standard Time'): -358,
 Timestamp('2020-06-30 00:00:00+0700', tz='SE Asia Standard Time'): -357,
 Timestamp('2020-07-01 00:00:00+0700', tz='SE Asia Standard Time'): -356,
 Timestamp('2020-07-02 00:00:00+0700', tz='SE Asia Standard Time'): -355,
 Timestamp('2020-07-03 00:00:00+0700', tz='SE Asia Standard Time'): -354,
 Timestamp('2020-07-04 00:00:00+0700', tz='SE Asia Standard Time'): -353,
 Timestamp('2020-07-05 00:00:00+0700', tz='SE Asia Standard Time'): -352,
 Timestamp('2020-07-06 00:00:00+0700', tz='SE Asia Standard Time'): -351,
 Timestamp('2020-07-07 00:00:00+0700', tz='SE Asia Standard Time'): -350,
 Timestamp('2020-07-08 00:00:00+0700', tz='SE Asia Standard Time'): -349,
 Timestamp('2020-07-09 00:00:00+0700', tz='SE Asia Standard Time'): -348,
 Timestamp('2020-07-10 00:00:00+0700', tz='SE Asia Standard Time'): -347,
 Timestamp('2020-07-11 00:00:00+0700', tz='SE Asia Standard Time'): -346,
 Timestamp('2020-07-12 00:00:00+0700', tz='SE Asia Standard Time'): -345,
 Timestamp('2020-07-13 00:00:00+0700', tz='SE Asia Standard Time'): -344,
 Timestamp('2020-07-14 00:00:00+0700', tz='SE Asia Standard Time'): -343,
 Timestamp('2020-07-15 00:00:00+0700', tz='SE Asia Standard Time'): -342,
 Timestamp('2020-07-16 00:00:00+0700', tz='SE Asia Standard Time'): -341,
 Timestamp('2020-07-17 00:00:00+0700', tz='SE Asia Standard Time'): -340,
 Timestamp('2020-07-18 00:00:00+0700', tz='SE Asia Standard Time'): -339,
 Timestamp('2020-07-19 00:00:00+0700', tz='SE Asia Standard Time'): -338,
 Timestamp('2020-07-20 00:00:00+0700', tz='SE Asia Standard Time'): -337,
 Timestamp('2020-07-21 00:00:00+0700', tz='SE Asia Standard Time'): -336,
 Timestamp('2020-07-22 00:00:00+0700', tz='SE Asia Standard Time'): -335,
 Timestamp('2020-07-23 00:00:00+0700', tz='SE Asia Standard Time'): -334,
 Timestamp('2020-07-24 00:00:00+0700', tz='SE Asia Standard Time'): -333,
 Timestamp('2020-07-25 00:00:00+0700', tz='SE Asia Standard Time'): -332,
 Timestamp('2020-07-26 00:00:00+0700', tz='SE Asia Standard Time'): -331,
 Timestamp('2020-07-27 00:00:00+0700', tz='SE Asia Standard Time'): -330,
 Timestamp('2020-07-28 00:00:00+0700', tz='SE Asia Standard Time'): -329,
 Timestamp('2020-07-29 00:00:00+0700', tz='SE Asia Standard Time'): -328,
 Timestamp('2020-07-30 00:00:00+0700', tz='SE Asia Standard Time'): -327,
 Timestamp('2020-07-31 00:00:00+0700', tz='SE Asia Standard Time'): -326,
 Timestamp('2020-08-01 00:00:00+0700', tz='SE Asia Standard Time'): -325,
 Timestamp('2020-08-02 00:00:00+0700', tz='SE Asia Standard Time'): -324,
 Timestamp('2020-08-03 00:00:00+0700', tz='SE Asia Standard Time'): -323,
 Timestamp('2020-08-04 00:00:00+0700', tz='SE Asia Standard Time'): -322,
 Timestamp('2020-08-05 00:00:00+0700', tz='SE Asia Standard Time'): -321,
 Timestamp('2020-08-06 00:00:00+0700', tz='SE Asia Standard Time'): -320,
 Timestamp('2020-08-07 00:00:00+0700', tz='SE Asia Standard Time'): -319,
 Timestamp('2020-08-08 00:00:00+0700', tz='SE Asia Standard Time'): -318,
 Timestamp('2020-08-09 00:00:00+0700', tz='SE Asia Standard Time'): -317,
 Timestamp('2020-08-10 00:00:00+0700', tz='SE Asia Standard Time'): -316,
 Timestamp('2020-08-11 00:00:00+0700', tz='SE Asia Standard Time'): -315,
 Timestamp('2020-08-12 00:00:00+0700', tz='SE Asia Standard Time'): -314,
 Timestamp('2020-08-13 00:00:00+0700', tz='SE Asia Standard Time'): -313,
 Timestamp('2020-08-14 00:00:00+0700', tz='SE Asia Standard Time'): -312,
 Timestamp('2020-08-15 00:00:00+0700', tz='SE Asia Standard Time'): -311,
 Timestamp('2020-08-16 00:00:00+0700', tz='SE Asia Standard Time'): -310,
 Timestamp('2020-08-17 00:00:00+0700', tz='SE Asia Standard Time'): -309,
 Timestamp('2020-08-18 00:00:00+0700', tz='SE Asia Standard Time'): -308,
 Timestamp('2020-08-19 00:00:00+0700', tz='SE Asia Standard Time'): -307,
 Timestamp('2020-08-20 00:00:00+0700', tz='SE Asia Standard Time'): -306,
 Timestamp('2020-08-21 00:00:00+0700', tz='SE Asia Standard Time'): -305,
 Timestamp('2020-08-22 00:00:00+0700', tz='SE Asia Standard Time'): -304,
 Timestamp('2020-08-23 00:00:00+0700', tz='SE Asia Standard Time'): -303,
 Timestamp('2020-08-24 00:00:00+0700', tz='SE Asia Standard Time'): -302,
 Timestamp('2020-08-25 00:00:00+0700', tz='SE Asia Standard Time'): -301,
 Timestamp('2020-08-26 00:00:00+0700', tz='SE Asia Standard Time'): -300,
 Timestamp('2020-08-27 00:00:00+0700', tz='SE Asia Standard Time'): -299,
 Timestamp('2020-08-28 00:00:00+0700', tz='SE Asia Standard Time'): -298,
 Timestamp('2020-08-29 00:00:00+0700', tz='SE Asia Standard Time'): -297,
 Timestamp('2020-08-30 00:00:00+0700', tz='SE Asia Standard Time'): -296,
 Timestamp('2020-08-31 00:00:00+0700', tz='SE Asia Standard Time'): -295,
 Timestamp('2020-09-01 00:00:00+0700', tz='SE Asia Standard Time'): -294,
 Timestamp('2020-09-02 00:00:00+0700', tz='SE Asia Standard Time'): -293,
 Timestamp('2020-09-03 00:00:00+0700', tz='SE Asia Standard Time'): -292,
 Timestamp('2020-09-04 00:00:00+0700', tz='SE Asia Standard Time'): -291,
 Timestamp('2020-09-05 00:00:00+0700', tz='SE Asia Standard Time'): -290,
 Timestamp('2020-09-06 00:00:00+0700', tz='SE Asia Standard Time'): -289,
 Timestamp('2020-09-07 00:00:00+0700', tz='SE Asia Standard Time'): -288,
 Timestamp('2020-09-08 00:00:00+0700', tz='SE Asia Standard Time'): -287,
 Timestamp('2020-09-09 00:00:00+0700', tz='SE Asia Standard Time'): -286,
 Timestamp('2020-09-10 00:00:00+0700', tz='SE Asia Standard Time'): -285,
 Timestamp('2020-09-11 00:00:00+0700', tz='SE Asia Standard Time'): -284,
 Timestamp('2020-09-12 00:00:00+0700', tz='SE Asia Standard Time'): -283,
 Timestamp('2020-09-13 00:00:00+0700', tz='SE Asia Standard Time'): -282,
 Timestamp('2020-09-14 00:00:00+0700', tz='SE Asia Standard Time'): -281,
 Timestamp('2020-09-15 00:00:00+0700', tz='SE Asia Standard Time'): -280,
 Timestamp('2020-09-16 00:00:00+0700', tz='SE Asia Standard Time'): -279,
 Timestamp('2020-09-17 00:00:00+0700', tz='SE Asia Standard Time'): -278,
 Timestamp('2020-09-18 00:00:00+0700', tz='SE Asia Standard Time'): -277,
 Timestamp('2020-09-19 00:00:00+0700', tz='SE Asia Standard Time'): -276,
 Timestamp('2020-09-20 00:00:00+0700', tz='SE Asia Standard Time'): -275,
 Timestamp('2020-09-21 00:00:00+0700', tz='SE Asia Standard Time'): -274,
 Timestamp('2020-09-22 00:00:00+0700', tz='SE Asia Standard Time'): -273,
 Timestamp('2020-09-23 00:00:00+0700', tz='SE Asia Standard Time'): -272,
 Timestamp('2020-09-24 00:00:00+0700', tz='SE Asia Standard Time'): -271,
 Timestamp('2020-09-25 00:00:00+0700', tz='SE Asia Standard Time'): -270,
 Timestamp('2020-09-26 00:00:00+0700', tz='SE Asia Standard Time'): -269,
 Timestamp('2020-09-27 00:00:00+0700', tz='SE Asia Standard Time'): -268,
 Timestamp('2020-09-28 00:00:00+0700', tz='SE Asia Standard Time'): -267,
 Timestamp('2020-09-29 00:00:00+0700', tz='SE Asia Standard Time'): -266,
 Timestamp('2020-09-30 00:00:00+0700', tz='SE Asia Standard Time'): -265,
 Timestamp('2020-10-01 00:00:00+0700', tz='SE Asia Standard Time'): -264,
 Timestamp('2020-10-02 00:00:00+0700', tz='SE Asia Standard Time'): -263,
 Timestamp('2020-10-03 00:00:00+0700', tz='SE Asia Standard Time'): -262,
 Timestamp('2020-10-04 00:00:00+0700', tz='SE Asia Standard Time'): -261,
 Timestamp('2020-10-05 00:00:00+0700', tz='SE Asia Standard Time'): -260,
 Timestamp('2020-10-06 00:00:00+0700', tz='SE Asia Standard Time'): -259,
 Timestamp('2020-10-07 00:00:00+0700', tz='SE Asia Standard Time'): -258,
 Timestamp('2020-10-08 00:00:00+0700', tz='SE Asia Standard Time'): -257,
 Timestamp('2020-10-09 00:00:00+0700', tz='SE Asia Standard Time'): -256,
 Timestamp('2020-10-10 00:00:00+0700', tz='SE Asia Standard Time'): -255,
 Timestamp('2020-10-11 00:00:00+0700', tz='SE Asia Standard Time'): -254,
 Timestamp('2020-10-12 00:00:00+0700', tz='SE Asia Standard Time'): -253,
 Timestamp('2020-10-13 00:00:00+0700', tz='SE Asia Standard Time'): -252,
 Timestamp('2020-10-14 00:00:00+0700', tz='SE Asia Standard Time'): -251,
 Timestamp('2020-10-15 00:00:00+0700', tz='SE Asia Standard Time'): -250,
 Timestamp('2020-10-16 00:00:00+0700', tz='SE Asia Standard Time'): -249,
 Timestamp('2020-10-17 00:00:00+0700', tz='SE Asia Standard Time'): -248,
 Timestamp('2020-10-18 00:00:00+0700', tz='SE Asia Standard Time'): -247,
 Timestamp('2020-10-19 00:00:00+0700', tz='SE Asia Standard Time'): -246,
 Timestamp('2020-10-20 00:00:00+0700', tz='SE Asia Standard Time'): -245,
 Timestamp('2020-10-21 00:00:00+0700', tz='SE Asia Standard Time'): -244,
 Timestamp('2020-10-22 00:00:00+0700', tz='SE Asia Standard Time'): -243,
 Timestamp('2020-10-23 00:00:00+0700', tz='SE Asia Standard Time'): -242,
 Timestamp('2020-10-24 00:00:00+0700', tz='SE Asia Standard Time'): -241,
 Timestamp('2020-10-25 00:00:00+0700', tz='SE Asia Standard Time'): -240,
 Timestamp('2020-10-26 00:00:00+0700', tz='SE Asia Standard Time'): -239,
 Timestamp('2020-10-27 00:00:00+0700', tz='SE Asia Standard Time'): -238,
 Timestamp('2020-10-28 00:00:00+0700', tz='SE Asia Standard Time'): -237,
 Timestamp('2020-10-29 00:00:00+0700', tz='SE Asia Standard Time'): -236,
 Timestamp('2020-10-30 00:00:00+0700', tz='SE Asia Standard Time'): -235,
 Timestamp('2020-10-31 00:00:00+0700', tz='SE Asia Standard Time'): -234,
 Timestamp('2020-11-01 00:00:00+0700', tz='SE Asia Standard Time'): -233,
 Timestamp('2020-11-02 00:00:00+0700', tz='SE Asia Standard Time'): -232,
 Timestamp('2020-11-03 00:00:00+0700', tz='SE Asia Standard Time'): -231,
 Timestamp('2020-11-04 00:00:00+0700', tz='SE Asia Standard Time'): -230,
 Timestamp('2020-11-05 00:00:00+0700', tz='SE Asia Standard Time'): -229,
 Timestamp('2020-11-06 00:00:00+0700', tz='SE Asia Standard Time'): -228,
 Timestamp('2020-11-07 00:00:00+0700', tz='SE Asia Standard Time'): -227,
 Timestamp('2020-11-08 00:00:00+0700', tz='SE Asia Standard Time'): -226,
 Timestamp('2020-11-09 00:00:00+0700', tz='SE Asia Standard Time'): -225,
 Timestamp('2020-11-10 00:00:00+0700', tz='SE Asia Standard Time'): -224,
 Timestamp('2020-11-11 00:00:00+0700', tz='SE Asia Standard Time'): -223,
 Timestamp('2020-11-12 00:00:00+0700', tz='SE Asia Standard Time'): -222,
 Timestamp('2020-11-13 00:00:00+0700', tz='SE Asia Standard Time'): -221,
 Timestamp('2020-11-14 00:00:00+0700', tz='SE Asia Standard Time'): -220,
 Timestamp('2020-11-15 00:00:00+0700', tz='SE Asia Standard Time'): -219,
 Timestamp('2020-11-16 00:00:00+0700', tz='SE Asia Standard Time'): -218,
 Timestamp('2020-11-17 00:00:00+0700', tz='SE Asia Standard Time'): -217,
 Timestamp('2020-11-18 00:00:00+0700', tz='SE Asia Standard Time'): -216,
 Timestamp('2020-11-19 00:00:00+0700', tz='SE Asia Standard Time'): -215,
 Timestamp('2020-11-20 00:00:00+0700', tz='SE Asia Standard Time'): -214,
 Timestamp('2020-11-21 00:00:00+0700', tz='SE Asia Standard Time'): -213,
 Timestamp('2020-11-22 00:00:00+0700', tz='SE Asia Standard Time'): -212,
 Timestamp('2020-11-23 00:00:00+0700', tz='SE Asia Standard Time'): -211,
 Timestamp('2020-11-24 00:00:00+0700', tz='SE Asia Standard Time'): -210,
 Timestamp('2020-11-25 00:00:00+0700', tz='SE Asia Standard Time'): -209,
 Timestamp('2020-11-26 00:00:00+0700', tz='SE Asia Standard Time'): -208,
 Timestamp('2020-11-27 00:00:00+0700', tz='SE Asia Standard Time'): -207,
 Timestamp('2020-11-28 00:00:00+0700', tz='SE Asia Standard Time'): -206,
 Timestamp('2020-11-29 00:00:00+0700', tz='SE Asia Standard Time'): -205,
 Timestamp('2020-11-30 00:00:00+0700', tz='SE Asia Standard Time'): -204,
 Timestamp('2020-12-01 00:00:00+0700', tz='SE Asia Standard Time'): -203,
 Timestamp('2020-12-02 00:00:00+0700', tz='SE Asia Standard Time'): -202,
 Timestamp('2020-12-03 00:00:00+0700', tz='SE Asia Standard Time'): -201,
 Timestamp('2020-12-04 00:00:00+0700', tz='SE Asia Standard Time'): -200,
 Timestamp('2020-12-05 00:00:00+0700', tz='SE Asia Standard Time'): -199,
 Timestamp('2020-12-06 00:00:00+0700', tz='SE Asia Standard Time'): -198,
 Timestamp('2020-12-07 00:00:00+0700', tz='SE Asia Standard Time'): -197,
 Timestamp('2020-12-08 00:00:00+0700', tz='SE Asia Standard Time'): -196,
 Timestamp('2020-12-09 00:00:00+0700', tz='SE Asia Standard Time'): -195,
 Timestamp('2020-12-10 00:00:00+0700', tz='SE Asia Standard Time'): -194,
 Timestamp('2020-12-11 00:00:00+0700', tz='SE Asia Standard Time'): -193,
 Timestamp('2020-12-12 00:00:00+0700', tz='SE Asia Standard Time'): -192,
 Timestamp('2020-12-13 00:00:00+0700', tz='SE Asia Standard Time'): -191,
 Timestamp('2020-12-14 00:00:00+0700', tz='SE Asia Standard Time'): -190,
 Timestamp('2020-12-15 00:00:00+0700', tz='SE Asia Standard Time'): -189,
 Timestamp('2020-12-16 00:00:00+0700', tz='SE Asia Standard Time'): -188,
 Timestamp('2020-12-17 00:00:00+0700', tz='SE Asia Standard Time'): -187,
 Timestamp('2020-12-18 00:00:00+0700', tz='SE Asia Standard Time'): -186,
 Timestamp('2020-12-19 00:00:00+0700', tz='SE Asia Standard Time'): -185,
 Timestamp('2020-12-20 00:00:00+0700', tz='SE Asia Standard Time'): -184,
 Timestamp('2020-12-21 00:00:00+0700', tz='SE Asia Standard Time'): -183,
 Timestamp('2020-12-22 00:00:00+0700', tz='SE Asia Standard Time'): -182,
 Timestamp('2020-12-23 00:00:00+0700', tz='SE Asia Standard Time'): -181,
 Timestamp('2020-12-24 00:00:00+0700', tz='SE Asia Standard Time'): -180,
 Timestamp('2020-12-25 00:00:00+0700', tz='SE Asia Standard Time'): -179,
 Timestamp('2020-12-26 00:00:00+0700', tz='SE Asia Standard Time'): -178,
 Timestamp('2020-12-27 00:00:00+0700', tz='SE Asia Standard Time'): -177,
 Timestamp('2020-12-28 00:00:00+0700', tz='SE Asia Standard Time'): -176,
 Timestamp('2020-12-29 00:00:00+0700', tz='SE Asia Standard Time'): -175,
 Timestamp('2020-12-30 00:00:00+0700', tz='SE Asia Standard Time'): -174,
 Timestamp('2020-12-31 00:00:00+0700', tz='SE Asia Standard Time'): -173,
 Timestamp('2021-01-01 00:00:00+0700', tz='SE Asia Standard Time'): -172,
 Timestamp('2021-01-02 00:00:00+0700', tz='SE Asia Standard Time'): -171,
 Timestamp('2021-01-03 00:00:00+0700', tz='SE Asia Standard Time'): -170,
 Timestamp('2021-01-04 00:00:00+0700', tz='SE Asia Standard Time'): -169,
 Timestamp('2021-01-05 00:00:00+0700', tz='SE Asia Standard Time'): -168,
 Timestamp('2021-01-06 00:00:00+0700', tz='SE Asia Standard Time'): -167,
 Timestamp('2021-01-07 00:00:00+0700', tz='SE Asia Standard Time'): -166,
 Timestamp('2021-01-08 00:00:00+0700', tz='SE Asia Standard Time'): -165,
 Timestamp('2021-01-09 00:00:00+0700', tz='SE Asia Standard Time'): -164,
 Timestamp('2021-01-10 00:00:00+0700', tz='SE Asia Standard Time'): -163,
 Timestamp('2021-01-11 00:00:00+0700', tz='SE Asia Standard Time'): -162,
 Timestamp('2021-01-12 00:00:00+0700', tz='SE Asia Standard Time'): -161,
 Timestamp('2021-01-13 00:00:00+0700', tz='SE Asia Standard Time'): -160,
 Timestamp('2021-01-14 00:00:00+0700', tz='SE Asia Standard Time'): -159,
 Timestamp('2021-01-15 00:00:00+0700', tz='SE Asia Standard Time'): -158,
 Timestamp('2021-01-16 00:00:00+0700', tz='SE Asia Standard Time'): -157,
 Timestamp('2021-01-17 00:00:00+0700', tz='SE Asia Standard Time'): -156,
 Timestamp('2021-01-18 00:00:00+0700', tz='SE Asia Standard Time'): -155,
 Timestamp('2021-01-19 00:00:00+0700', tz='SE Asia Standard Time'): -154,
 Timestamp('2021-01-20 00:00:00+0700', tz='SE Asia Standard Time'): -153,
 Timestamp('2021-01-21 00:00:00+0700', tz='SE Asia Standard Time'): -152,
 Timestamp('2021-01-22 00:00:00+0700', tz='SE Asia Standard Time'): -151,
 Timestamp('2021-01-23 00:00:00+0700', tz='SE Asia Standard Time'): -150,
 Timestamp('2021-01-24 00:00:00+0700', tz='SE Asia Standard Time'): -149,
 Timestamp('2021-01-25 00:00:00+0700', tz='SE Asia Standard Time'): -148,
 Timestamp('2021-01-26 00:00:00+0700', tz='SE Asia Standard Time'): -147,
 Timestamp('2021-01-27 00:00:00+0700', tz='SE Asia Standard Time'): -146,
 Timestamp('2021-01-28 00:00:00+0700', tz='SE Asia Standard Time'): -145,
 Timestamp('2021-01-29 00:00:00+0700', tz='SE Asia Standard Time'): -144,
 Timestamp('2021-01-30 00:00:00+0700', tz='SE Asia Standard Time'): -143,
 Timestamp('2021-01-31 00:00:00+0700', tz='SE Asia Standard Time'): -142,
 Timestamp('2021-02-01 00:00:00+0700', tz='SE Asia Standard Time'): -141,
 Timestamp('2021-02-02 00:00:00+0700', tz='SE Asia Standard Time'): -140,
 Timestamp('2021-02-03 00:00:00+0700', tz='SE Asia Standard Time'): -139,
 Timestamp('2021-02-04 00:00:00+0700', tz='SE Asia Standard Time'): -138,
 Timestamp('2021-02-05 00:00:00+0700', tz='SE Asia Standard Time'): -137,
 Timestamp('2021-02-06 00:00:00+0700', tz='SE Asia Standard Time'): -136,
 Timestamp('2021-02-07 00:00:00+0700', tz='SE Asia Standard Time'): -135,
 Timestamp('2021-02-08 00:00:00+0700', tz='SE Asia Standard Time'): -134,
 Timestamp('2021-02-09 00:00:00+0700', tz='SE Asia Standard Time'): -133,
 Timestamp('2021-02-10 00:00:00+0700', tz='SE Asia Standard Time'): -132,
 Timestamp('2021-02-11 00:00:00+0700', tz='SE Asia Standard Time'): -131,
 Timestamp('2021-02-12 00:00:00+0700', tz='SE Asia Standard Time'): -130,
 Timestamp('2021-02-13 00:00:00+0700', tz='SE Asia Standard Time'): -129,
 Timestamp('2021-02-14 00:00:00+0700', tz='SE Asia Standard Time'): -128,
 Timestamp('2021-02-15 00:00:00+0700', tz='SE Asia Standard Time'): -127,
 Timestamp('2021-02-16 00:00:00+0700', tz='SE Asia Standard Time'): -126,
 Timestamp('2021-02-17 00:00:00+0700', tz='SE Asia Standard Time'): -125,
 Timestamp('2021-02-18 00:00:00+0700', tz='SE Asia Standard Time'): -124,
 Timestamp('2021-02-19 00:00:00+0700', tz='SE Asia Standard Time'): -123,
 Timestamp('2021-02-20 00:00:00+0700', tz='SE Asia Standard Time'): -122,
 Timestamp('2021-02-21 00:00:00+0700', tz='SE Asia Standard Time'): -121,
 Timestamp('2021-02-22 00:00:00+0700', tz='SE Asia Standard Time'): -120,
 Timestamp('2021-02-23 00:00:00+0700', tz='SE Asia Standard Time'): -119,
 Timestamp('2021-02-24 00:00:00+0700', tz='SE Asia Standard Time'): -118,
 Timestamp('2021-02-25 00:00:00+0700', tz='SE Asia Standard Time'): -117,
 Timestamp('2021-02-26 00:00:00+0700', tz='SE Asia Standard Time'): -116,
 Timestamp('2021-02-27 00:00:00+0700', tz='SE Asia Standard Time'): -115,
 Timestamp('2021-02-28 00:00:00+0700', tz='SE Asia Standard Time'): -114,
 Timestamp('2021-03-01 00:00:00+0700', tz='SE Asia Standard Time'): -113,
 Timestamp('2021-03-02 00:00:00+0700', tz='SE Asia Standard Time'): -112,
 Timestamp('2021-03-03 00:00:00+0700', tz='SE Asia Standard Time'): -111,
 Timestamp('2021-03-04 00:00:00+0700', tz='SE Asia Standard Time'): -110,
 Timestamp('2021-03-05 00:00:00+0700', tz='SE Asia Standard Time'): -109,
 Timestamp('2021-03-06 00:00:00+0700', tz='SE Asia Standard Time'): -108,
 Timestamp('2021-03-07 00:00:00+0700', tz='SE Asia Standard Time'): -107,
 Timestamp('2021-03-08 00:00:00+0700', tz='SE Asia Standard Time'): -106,
 Timestamp('2021-03-09 00:00:00+0700', tz='SE Asia Standard Time'): -105,
 Timestamp('2021-03-10 00:00:00+0700', tz='SE Asia Standard Time'): -104,
 Timestamp('2021-03-11 00:00:00+0700', tz='SE Asia Standard Time'): -103,
 Timestamp('2021-03-12 00:00:00+0700', tz='SE Asia Standard Time'): -102,
 Timestamp('2021-03-13 00:00:00+0700', tz='SE Asia Standard Time'): -101,
 Timestamp('2021-03-14 00:00:00+0700', tz='SE Asia Standard Time'): -100,
 Timestamp('2021-03-15 00:00:00+0700', tz='SE Asia Standard Time'): -99,
 Timestamp('2021-03-16 00:00:00+0700', tz='SE Asia Standard Time'): -98,
 Timestamp('2021-03-17 00:00:00+0700', tz='SE Asia Standard Time'): -97,
 Timestamp('2021-03-18 00:00:00+0700', tz='SE Asia Standard Time'): -96,

Ngoài ra ta cũng có `total_days` là tổng số ngày chạy của problem và `problem_start_date` là ngày chạy sớm nhất của các campaign để tiền xử lí places và campaigns

In [18]:
print(f"Problem này kéo dài trong {total_running_days} ngày, ngày xuất phát là {problem_start_date}")

Problem này kéo dài trong 101 ngày, ngày xuất phát là 2021-06-22 00:00:00+07:00

### 3.2 Preprocess Places

Phần này sẽ mô tả cách places được xử lí từ _raw_ thành _preprocessed_, nằm trong hàm `_preprocess_places()`.

Bước đầu tiên dưới đây, chuyển `raw_places` từ dict thành 1 dataframe, đồng thời gán `solve_id` (cột solve_id) cho từng địa điểm và sort theo cột này. Chạy cell dưới:

In [19]:
df_places = PreprocessConverter.raw_places_to_df(raw_places)
df_places

,_id,problemId,placeId,ctrs,views,profilesRatio,shareRate,createDate,shareType,solve_id
0,60d1a82016b3330442537247,60d1a81f16b3330442537211,4827998237552142792,"[{'value': 1.0, 'type': 'DEFAULT'}, {'type': '...","[{'date': 2021-06-22 00:00:00+07:00, 'value': ...","[{'type': 'AGE', 'ratio': [0.0023422095, 0.045...",0.30,2021-06-22 09:06:40.019000+00:00,SOFT,0
1,60d1a82016b3330442537248,60d1a81f16b3330442537211,4857469430519615278,"[{'value': 1.0, 'type': 'DEFAULT'}, {'type': '...","[{'date': 2021-06-22 00:00:00+07:00, 'value': ...","[{'type': 'AGE', 'ratio': [0.030948842, 0.2369...",0.50,2021-06-22 09:06:40.030000+00:00,SOFT,1
2,60d1a82016b3330442537249,60d1a81f16b3330442537211,5538742900884010760,"[{'value': 1.0, 'type': 'DEFAULT'}, {'type': '...","[{'date': 2021-06-22 00:00:00+07:00, 'value': ...","[{'type': 'AGE', 'ratio': [0.058693647, 0.4471...",1.00,2021-06-22 09:06:40.041000+00:00,SOFT,2
3,60d1a82016b333044253724a,60d1a81f16b3330442537211,100,"[{'value': 0.9999999, 'type': 'DEFAULT'}, {'ty...","[{'date': 2021-06-22 00:00:00+07:00, 'value': ...","[{'type': 'AGE', 'ratio': [0.0, 0.0, 0.0, 0.0,...",0.50,2021-06-22 09:06:40.046000+00:00,NETWORK_HARD,3
4,60d1a82016b333044253724b,60d1a81f16b3330442537211,5577578545256809161,"[{'value': 1.0, 'type': 'DEFAULT'}, {'type': '...","[{'date': 2021-06-22 00:00:00+07:00, 'value': ...","[{'type': 'AGE', 'ratio': [0.0, 0.0, 0.0, 0.0,...",1.00,2021-06-22 09:06:40.056000+00:00,SOFT,4
5,60d1a82016b333044253724c,60d1a81f16b3330442537211,5023173597424371233,"[{'value': 1.0, 'type': 'DEFAULT'}, {'type': '...","[{'date': 2021-06-22 00:00:00+07:00, 'value': ...","[{'type': 'AGE', 'ratio': [0.04574774, 0.28752...",0.70,2021-06-22 09:06:40.067000+00:00,SOFT,5
6,60d1a82016b333044253724d,60d1a81f16b3330442537211,4979871131880682040,"[{'value': 1.0, 'type': 'DEFAULT'}, {'type': '...","[{'date': 2021-06-22 00:00:00+07:00, 'value': ...","[{'type': 'AGE', 'ratio': [0.0, 0.0, 0.0, 0.0,...",0.50,2021-06-22 09:06:40.076000+00:00,SOFT,6
7,60d1a82016b333044253724e,60d1a81f16b3330442537211,5181053909251379448,"[{'value': 1.0, 'type': 'DEFAULT'}, {'type': '...","[{'date': 2021-06-22 00:00:00+07:00, 'value': ...","[{'type': 'AGE', 'ratio': [0.0092105735, 0.105...",0.35,2021-06-22 09:06:40.079000+00:00,SOFT,7

Đổi tên cell các cột `placeId`, `shareType`:

In [20]:
df_places = df_places.rename(columns= {'placeId':'original_id', 'shareType': 'share_type'})

Hàm dưới chuyển giá trị cột __ctrs__ về thành 1 list các giá trị ctr thứ tự nhằm dễ dàng xử lí về sau.

In [21]:
df_places['ctrs'] = PreprocessConverter.get_ctrs_list(df_places)
df_places

,_id,problemId,original_id,ctrs,views,profilesRatio,shareRate,createDate,share_type,solve_id
0,60d1a82016b3330442537247,60d1a81f16b3330442537211,4827998237552142792,"[1.0, 0.6499999, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2,...","[{'date': 2021-06-22 00:00:00+07:00, 'value': ...","[{'type': 'AGE', 'ratio': [0.0023422095, 0.045...",0.30,2021-06-22 09:06:40.019000+00:00,SOFT,0
1,60d1a82016b3330442537248,60d1a81f16b3330442537211,4857469430519615278,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[{'date': 2021-06-22 00:00:00+07:00, 'value': ...","[{'type': 'AGE', 'ratio': [0.030948842, 0.2369...",0.50,2021-06-22 09:06:40.030000+00:00,SOFT,1
2,60d1a82016b3330442537249,60d1a81f16b3330442537211,5538742900884010760,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[{'date': 2021-06-22 00:00:00+07:00, 'value': ...","[{'type': 'AGE', 'ratio': [0.058693647, 0.4471...",1.00,2021-06-22 09:06:40.041000+00:00,SOFT,2
3,60d1a82016b333044253724a,60d1a81f16b3330442537211,100,"[0.9999999, 0.6499999, 0.49999994, 0.49999994,...","[{'date': 2021-06-22 00:00:00+07:00, 'value': ...","[{'type': 'AGE', 'ratio': [0.0, 0.0, 0.0, 0.0,...",0.50,2021-06-22 09:06:40.046000+00:00,NETWORK_HARD,3
4,60d1a82016b333044253724b,60d1a81f16b3330442537211,5577578545256809161,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[{'date': 2021-06-22 00:00:00+07:00, 'value': ...","[{'type': 'AGE', 'ratio': [0.0, 0.0, 0.0, 0.0,...",1.00,2021-06-22 09:06:40.056000+00:00,SOFT,4
5,60d1a82016b333044253724c,60d1a81f16b3330442537211,5023173597424371233,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[{'date': 2021-06-22 00:00:00+07:00, 'value': ...","[{'type': 'AGE', 'ratio': [0.04574774, 0.28752...",0.70,2021-06-22 09:06:40.067000+00:00,SOFT,5
6,60d1a82016b333044253724d,60d1a81f16b3330442537211,4979871131880682040,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[{'date': 2021-06-22 00:00:00+07:00, 'value': ...","[{'type': 'AGE', 'ratio': [0.0, 0.0, 0.0, 0.0,...",0.50,2021-06-22 09:06:40.076000+00:00,SOFT,6
7,60d1a82016b333044253724e,60d1a81f16b3330442537211,5181053909251379448,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[{'date': 2021-06-22 00:00:00+07:00, 'value': ...","[{'type': 'AGE', 'ratio': [0.0092105735, 0.105...",0.35,2021-06-22 09:06:40.079000+00:00,SOFT,7

Tương tự, hàm dưới chuyển cột views thành 1 list các giá trị view tương ứng với các ngày 0,1,2,...

In [22]:
df_places = PreprocessConverter._convert_views_date_to_int(date_int_mapper, df_places, total_running_days)
df_places

,_id,problemId,original_id,ctrs,views,profilesRatio,shareRate,createDate,share_type,solve_id
0,60d1a82016b3330442537247,60d1a81f16b3330442537211,4827998237552142792,"[1.0, 0.6499999, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2,...","[2567.027, 2196.5522, 2248.2507, 2306.9858, 26...","[{'type': 'AGE', 'ratio': [0.0023422095, 0.045...",0.30,2021-06-22 09:06:40.019000+00:00,SOFT,0
1,60d1a82016b3330442537248,60d1a81f16b3330442537211,4857469430519615278,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[37766.0, 38116.0, 37709.0, 38103.0, 39131.0, ...","[{'type': 'AGE', 'ratio': [0.030948842, 0.2369...",0.50,2021-06-22 09:06:40.030000+00:00,SOFT,1
2,60d1a82016b3330442537249,60d1a81f16b3330442537211,5538742900884010760,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[13958.0, 15978.0, 16311.0, 19287.0, 20159.0, ...","[{'type': 'AGE', 'ratio': [0.058693647, 0.4471...",1.00,2021-06-22 09:06:40.041000+00:00,SOFT,2
3,60d1a82016b333044253724a,60d1a81f16b3330442537211,100,"[0.9999999, 0.6499999, 0.49999994, 0.49999994,...","[656.7423, 626.5345, 640.19836, 704.70953, 710...","[{'type': 'AGE', 'ratio': [0.0, 0.0, 0.0, 0.0,...",0.50,2021-06-22 09:06:40.046000+00:00,NETWORK_HARD,3
4,60d1a82016b333044253724b,60d1a81f16b3330442537211,5577578545256809161,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[12.3321, 13.1939, 13.7667, 14.519, 15.2452, 1...","[{'type': 'AGE', 'ratio': [0.0, 0.0, 0.0, 0.0,...",1.00,2021-06-22 09:06:40.056000+00:00,SOFT,4
5,60d1a82016b333044253724c,60d1a81f16b3330442537211,5023173597424371233,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[14904.0, 15146.0, 16161.0, 17219.0, 17635.0, ...","[{'type': 'AGE', 'ratio': [0.04574774, 0.28752...",0.70,2021-06-22 09:06:40.067000+00:00,SOFT,5
6,60d1a82016b333044253724d,60d1a81f16b3330442537211,4979871131880682040,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[0.796179, 0.556209, 0.662812, 0.99081, 0.4860...","[{'type': 'AGE', 'ratio': [0.0, 0.0, 0.0, 0.0,...",0.50,2021-06-22 09:06:40.076000+00:00,SOFT,6
7,60d1a82016b333044253724e,60d1a81f16b3330442537211,5181053909251379448,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[213.0, 179.0, 195.0, 215.0, 146.0, 153.0, 231...","[{'type': 'AGE', 'ratio': [0.0092105735, 0.105...",0.35,2021-06-22 09:06:40.079000+00:00,SOFT,7

Hàm dưới tạo thêm 1 cột __profiles_ratio__<br>
Giá trị trong các ô đấy là đối tượng `PlaceProfile`. Chi tiết sẽ được doc ở phía dưới. Còn để nói qua thì:<br>
Mỗi `PlaceProfile` có 3 attribute:<br>

* `PlaceProfile.db_rep`: Giá trị lấy ra từ db. Ví dụ:<br>
`[{'type': 'AGE',
  'ratio': [0.0023422095,
   0.04535171,
   0.06319563,
   0.045249052,
   0.024730375,
   0.014243808,
   0.025496023,
   0.77939117]},
 {'ratio': [0.118145056, 0.10246408, 0.7793909], 'type': 'GENDER'}]`<br>
* `PlaceProfile.list_rep`: Gía trị profile đã chuyển về các list của các profile. Ví dụ: <br>
`[[0.118145056, 0.10246408, 0.7793909],
[0.0023422095,
0.04535171,
0.06319563,
0.045249052,
0.024730375,
0.014243808,
0.025496023,
0.77939117]]`
* `PlaceProfile.int_rep`: Giá trị chuyển 1 list như hình dưới. Ví dụ: <br>
`[0.000276720472541232,
0.005358080317645761,
0.007466251245305281,
0.005345951782486912,
0.002921771539276,
0.001682835493813248,
0.003012229065112288,
0.09208121342555552,
0.00023999234158476003,
0.0046469212415768,
0.0064752820879704,
0.00463640248405216,
0.0025339751224299997,
0.00145947868241664,
0.00261242654035384,
0.0798595991941736,
0.0018254967701935502,
0.035346710073439,
0.049254098941767,
0.035266699362426795,
0.019274629228587498,
0.0111014943365472,
0.0198713683123907,
0.6074503854383531]`

In [23]:
df_places["profiles_ratio"] = [PlaceProfile(profile_db_rep) for profile_db_rep in df_places['profilesRatio']]
df_places

,_id,problemId,original_id,ctrs,views,profilesRatio,shareRate,createDate,share_type,solve_id,profiles_ratio
0,60d1a82016b3330442537247,60d1a81f16b3330442537211,4827998237552142792,"[1.0, 0.6499999, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2,...","[2567.027, 2196.5522, 2248.2507, 2306.9858, 26...","[{'type': 'AGE', 'ratio': [0.0023422095, 0.045...",0.30,2021-06-22 09:06:40.019000+00:00,SOFT,0,<solver_helpers.PlaceProfile object at 0x00000...
1,60d1a82016b3330442537248,60d1a81f16b3330442537211,4857469430519615278,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[37766.0, 38116.0, 37709.0, 38103.0, 39131.0, ...","[{'type': 'AGE', 'ratio': [0.030948842, 0.2369...",0.50,2021-06-22 09:06:40.030000+00:00,SOFT,1,<solver_helpers.PlaceProfile object at 0x00000...
2,60d1a82016b3330442537249,60d1a81f16b3330442537211,5538742900884010760,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[13958.0, 15978.0, 16311.0, 19287.0, 20159.0, ...","[{'type': 'AGE', 'ratio': [0.058693647, 0.4471...",1.00,2021-06-22 09:06:40.041000+00:00,SOFT,2,<solver_helpers.PlaceProfile object at 0x00000...
3,60d1a82016b333044253724a,60d1a81f16b3330442537211,100,"[0.9999999, 0.6499999, 0.49999994, 0.49999994,...","[656.7423, 626.5345, 640.19836, 704.70953, 710...","[{'type': 'AGE', 'ratio': [0.0, 0.0, 0.0, 0.0,...",0.50,2021-06-22 09:06:40.046000+00:00,NETWORK_HARD,3,<solver_helpers.PlaceProfile object at 0x00000...
4,60d1a82016b333044253724b,60d1a81f16b3330442537211,5577578545256809161,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[12.3321, 13.1939, 13.7667, 14.519, 15.2452, 1...","[{'type': 'AGE', 'ratio': [0.0, 0.0, 0.0, 0.0,...",1.00,2021-06-22 09:06:40.056000+00:00,SOFT,4,<solver_helpers.PlaceProfile object at 0x00000...
5,60d1a82016b333044253724c,60d1a81f16b3330442537211,5023173597424371233,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[14904.0, 15146.0, 16161.0, 17219.0, 17635.0, ...","[{'type': 'AGE', 'ratio': [0.04574774, 0.28752...",0.70,2021-06-22 09:06:40.067000+00:00,SOFT,5,<solver_helpers.PlaceProfile object at 0x00000...
6,60d1a82016b333044253724d,60d1a81f16b3330442537211,4979871131880682040,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[0.796179, 0.556209, 0.662812, 0.99081, 0.4860...","[{'type': 'AGE', 'ratio': [0.0, 0.0, 0.0, 0.0,...",0.50,2021-06-22 09:06:40.076000+00:00,SOFT,6,<solver_helpers.PlaceProfile object at 0x00000...
7,60d1a82016b333044253724e,60d1a81f16b3330442537211,5181053909251379448,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[213.0, 179.0, 195.0, 215.0, 146.0, 153.0, 231...","[{'type': 'AGE', 'ratio': [0.0092105735, 0.105...",0.35,2021-06-22 09:06:40.079000+00:00,SOFT,7,<solver_helpers.PlaceProfile object at 0x00000...

Có thể chạy cell bên dưới để hiểu rõ hơn giá trị của `PlaceProfile`

In [24]:
place_profile = df_places['profiles_ratio'][0]
print(f"db_rep: {place_profile.db_rep}")
print(f"list_rep: {place_profile.list_rep}")
print(f"int_rep:{place_profile.int_rep}")

db_rep: [{'type': 'AGE', 'ratio': [0.0023422095, 0.04535171, 0.06319563, 0.045249052, 0.024730375, 0.014243808, 0.025496023, 0.77939117]}, {'ratio': [0.118145056, 0.10246408, 0.7793909], 'type': 'GENDER'}]
list_rep: [[0.118145056, 0.10246408, 0.7793909], [0.0023422095, 0.04535171, 0.06319563, 0.045249052, 0.024730375, 0.014243808, 0.025496023, 0.77939117]]
int_rep:[0.000276720472541232, 0.005358080317645761, 0.007466251245305281, 0.005345951782486912, 0.002921771539276, 0.001682835493813248, 0.003012229065112288, 0.09208121342555552, 0.00023999234158476003, 0.0046469212415768, 0.0064752820879704, 0.00463640248405216, 0.0025339751224299997, 0.00145947868241664, 0.00261242654035384, 0.0798595991941736, 0.0018254967701935502, 0.035346710073439, 0.049254098941767, 0.035266699362426795, 0.019274629228587498, 0.0111014943365472, 0.0198713683123907, 0.6074503854383531]

2 hàm dưới đổi tên cột, xóa tên cột các thứ

In [25]:
df_places.rename(columns={'shareRate':'share_rate'} , inplace= True)
df_places.drop(columns = ['_id', 'profilesRatio', 'problemId'], inplace = True, errors='ignore')

Hàm dưới đổi cột `share_type` về dạng int tương ứng (0 là `SOFT`, 1 là `HARD`)

In [26]:
df_places['share_type'] = df_places['share_type'].apply(lambda x: acm_base_pb2.ShareType.Value(x))
df_places

,original_id,ctrs,views,share_rate,createDate,share_type,solve_id,profiles_ratio
0,4827998237552142792,"[1.0, 0.6499999, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2,...","[2567.027, 2196.5522, 2248.2507, 2306.9858, 26...",0.30,2021-06-22 09:06:40.019000+00:00,0,0,<solver_helpers.PlaceProfile object at 0x00000...
1,4857469430519615278,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[37766.0, 38116.0, 37709.0, 38103.0, 39131.0, ...",0.50,2021-06-22 09:06:40.030000+00:00,0,1,<solver_helpers.PlaceProfile object at 0x00000...
2,5538742900884010760,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[13958.0, 15978.0, 16311.0, 19287.0, 20159.0, ...",1.00,2021-06-22 09:06:40.041000+00:00,0,2,<solver_helpers.PlaceProfile object at 0x00000...
3,100,"[0.9999999, 0.6499999, 0.49999994, 0.49999994,...","[656.7423, 626.5345, 640.19836, 704.70953, 710...",0.50,2021-06-22 09:06:40.046000+00:00,1,3,<solver_helpers.PlaceProfile object at 0x00000...
4,5577578545256809161,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[12.3321, 13.1939, 13.7667, 14.519, 15.2452, 1...",1.00,2021-06-22 09:06:40.056000+00:00,0,4,<solver_helpers.PlaceProfile object at 0x00000...
5,5023173597424371233,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[14904.0, 15146.0, 16161.0, 17219.0, 17635.0, ...",0.70,2021-06-22 09:06:40.067000+00:00,0,5,<solver_helpers.PlaceProfile object at 0x00000...
6,4979871131880682040,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[0.796179, 0.556209, 0.662812, 0.99081, 0.4860...",0.50,2021-06-22 09:06:40.076000+00:00,0,6,<solver_helpers.PlaceProfile object at 0x00000...
7,5181053909251379448,"[1.0, 0.65, 0.5, 0.5, 0.6, 0.6, 0.5, 0.2, 0.45...","[213.0, 179.0, 195.0, 215.0, 146.0, 153.0, 231...",0.35,2021-06-22 09:06:40.079000+00:00,0,7,<solver_helpers.PlaceProfile object at 0x00000...

DataFrame ở trên chính là `preprocessed_data.places`<br>
Cuối cùng 2 hàm dưới để tạo ra 1 place_mapper

In [27]:
places_mapper = pd.DataFrame({'original_id' : df_places['original_id'].to_list(), 'solve_id' : df_places['solve_id'].to_list()})
places_mapper_solve_to_orginal_dict = {solve : original for solve, original in  zip(df_places['solve_id'],df_places['original_id'])}
print(f'Place Mapper: {places_mapper_solve_to_orginal_dict}')

Place Mapper: {0: 4827998237552142792, 1: 4857469430519615278, 2: 5538742900884010760, 3: 100, 4: 5577578545256809161, 5: 5023173597424371233, 6: 4979871131880682040, 7: 5181053909251379448}

### 3.3 Preprocess campaigns

Phần này sẽ mô tả cách campaigns được xử lí từ _raw_ thành _preprocessed_ , nằm trong hàm `_preprocess_campaigns()`.

Lấy raw_data_campaigns:

In [28]:
raw_data, lower_ratio = solver_helpers.query_raw_data(problem_id)
raw_data = utils.CorrectRawData.correct(raw_data, adjust_start_date)
raw_campaigns = raw_data.campaigns

Bước đầu tiên dưới đây, chuyển `raw_campaigns` từ dict thành 1 dataframe, đồng thời gán `solve_id` (cột solve_id) cho từng campaign và sort theo cột này.`t_0` ở đây là index cuối cùng của các campaign network, các campaign có `solve_id` từ 0 đến `t_0` là Network, và sau đó là campaign domain:

In [29]:
df_campaigns,t_0 = PreprocessConverter._campaigns_to_df(raw_campaigns)
df_campaigns

,_id,problemId,campaignId,isNetwork,startDate,expiredDate,priority,type,total,placeIds,weights,profiles,createDate,solve_id
0,60d1a82016b3330442537212,60d1a81f16b3330442537211,4768939651732014836_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",[],"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.991000+00:00,0
1,60d1a82016b3330442537213,60d1a81f16b3330442537211,4768939651732014836_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],[],"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.992000+00:00,1
2,60d1a82016b3330442537214,60d1a81f16b3330442537211,4810238136557669178_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.992000+00:00,2
3,60d1a82016b3330442537215,60d1a81f16b3330442537211,4810238136557669178_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.992000+00:00,3
4,60d1a82016b3330442537216,60d1a81f16b3330442537211,5247609002361599862_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.993000+00:00,4
5,60d1a82016b3330442537217,60d1a81f16b3330442537211,5247609002361599862_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.993000+00:00,5
6,60d1a82016b3330442537218,60d1a81f16b3330442537211,5275363820481263653_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",[],"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.993000+00:00,6
7,60d1a82016b3330442537219,60d1a81f16b3330442537211,5275363820481263653_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],[],"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.994000+00:00,7
8,60d1a82016b333044253721a,60d1a81f16b3330442537211,5322575190744422716_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,166924.75,"[4979871131880682040, 5181053909251379448, 485...","[{'date': 2021-02-02 00:00:00+07:00, 'value': ...",[],2021-06-22 09:06:39.994000+00:00,8
9,60d1a82016b333044253721b,60d1a81f16b3330442537211,5322575190744422716_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,19235.00,[5181053909251379448],"[{'date': 2021-02-02 00:00:00+07:00, 'value': ...",[],2021-06-22 09:06:39.994000+00:00,9
10,60d1a82016b333044253721c,60d1a81f16b3330442537211,5370791925364426073_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...","[{'date': 2021-02-02 00:00:00+07:00, 'value': ...",[],2021-06-22 09:06:39.995000+00:00,10
11,60d1a82016b333044253721d,60d1a81f16b3330442537211,5370791925364426073_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],"[{'date': 2021-02-02 00:00:00+07:00, 'value': ...",[],2021-06-22 09:06:39.995000+00:00,11
12,60d1a82016b333044253721e,60d1a81f16b3330442537211,5387657435205013825_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",[],"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.995000+00:00,12
13,60d1a82016b333044253721f,60d1a81f16b3330442537211,5387657435205013825_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],[],"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.996000+00:00,13
14,60d1a82016b3330442537220,60d1a81f16b3330442537211,5400965728863573515_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.996000+00:00,14
15,60d1a82016b3330442537221,60d1a81f16b3330442537211,5400965728863573515_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.996000+00:00,15
16,60d1a82016b3330442537224,60d1a81f16b3330442537211,5577398347147938092_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.997000+00:00,16
17,60d1a82016b3330442537225,60d1a81f16b3330442537211,5577398347147938092_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.997000+00:00,17
18,60d1a82016b3330442537227,60d1a81f16b3330442537211,4650504253994331355_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,2589239.00,[4857469430519615278],[],[],2021-06-22 09:06:39.998000+00:00,18
19,60d1a82016b3330442537228,60d1a81f16b3330442537211,4713760987931352697_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,4240000.00,[5023173597424371233],[],[],2021-06-22 09:06:39.998000+00:00,19
20,60d1a82016b3330442537229,60d1a81f16b3330442537211,4718198705721931407_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],[],"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.999000+00:00,20
21,60d1a82016b333044253722a,60d1a81f16b3330442537211,4741325520555630568_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40+00:00,21
22,60d1a82016b333044253722b,60d1a81f16b3330442537211,4796633772157943273_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],[],"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.001000+00:00,22
23,60d1a82016b333044253722d,60d1a81f16b3330442537211,4823653667180754890_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,1229684.00,[5538742900884010760],[],[],2021-06-22 09:06:40.001000+00:00,23
24,60d1a82016b333044253722e,60d1a81f16b3330442537211,4824859557802329616_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],[],"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.002000+00:00,24
25,60d1a82016b333044253722f,60d1a81f16b3330442537211,4904151939315150524_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.002000+00:00,25
26,60d1a82016b3330442537231,60d1a81f16b3330442537211,4987628296907052401_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],[],"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.003000+00:00,26
27,60d1a82016b3330442537232,60d1a81f16b3330442537211,5004060173322688003_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.003000+00:00,27
28,60d1a82016b3330442537233,60d1a81f16b3330442537211,5005141348821177586_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],[],"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.004000+00:00,28
29,60d1a82016b3330442537234,60d1a81f16b3330442537211,5008562159266208975_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],[],"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.004000+00:00,29
30,60d1a82016b3330442537235,60d1a81f16b3330442537211,5112510634931261580_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.005000+00:00,30
31,60d1a82016b3330442537236,60d1a81f16b3330442537211,5116176280026807920_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.005000+00:00,31
32,60d1a82016b3330442537237,60d1a81f16b3330442537211,5140955443670820219_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.005000+00:00,32
33,60d1a82016b3330442537238,60d1a81f16b3330442537211,5144070500760291817_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.006000+00:00,33
34,60d1a82016b3330442537239,60d1a81f16b3330442537211,5145360317263062170_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,163588.39,[4827998237552142792],[],[],2021-06-22 09:06:40.006000+00:00,34
35,60d1a82016b333044253723b,60d1a81f16b3330442537211,5261690011954745524_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.007000+00:00,35
36,60d1a82016b333044253723c,60d1a81f16b3330442537211,5326884055688590955_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,1118869.00,[5023173597424371233],[],[],2021-06-22 09:06:40.007000+00:00,36
37,60d1a82016b333044253723d,60d1a81f16b3330442537211,5349652368050952557_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,4120000.00,[4857469430519615278],[],[],2021-06-22 09:06:40.008000+00:00,37
38,60d1a82016b333044253723e,60d1a81f16b3330442537211,5351581853241914431_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.008000+00:00,38
39,60d1a82016b333044253723f,60d1a81f16b3330442537211,5430288141589897773_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.008000+00:00,39
40,60d1a82016b3330442537240,60d1a81f16b3330442537211,5447298725065630394_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.009000+00:00,40
41,60d1a82016b3330442537241,60d1a81f16b3330442537211,5471706532034127453_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,4180000.00,[5538742900884010760],[],[],2021-06-22 09:06:40.009000+00:00,41
42,60d1a82016b3330442537242,60d1a81f16b3330442537211,5596899021949443719_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,140000.00,[4827998237552142792],[],[],2021-06-22 09:06:40.010000+00:00,42
43,60d1a82016b3330442537243,60d1a81f16b3330442537211,5609987844990570937_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],[],"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.010000+00:00,43
44,60d1a82016b3330442537244,60d1a81f16b3330442537211,5646870611503620553_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],[],"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.011000+00:00,44
45,60d1a82016b3330442537245,60d1a81f16b3330442537211,5678313728368360859_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],[],"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.011000+00:00,45
46,60d1a82016b3330442537246,60d1a81f16b3330442537211,5740071104871774323_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],[],"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.012000+00:00,46
47,60d1a82016b3330442537222,60d1a81f16b3330442537211,5438574239652778058_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_A,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...","[{'date': 2021-02-02 00:00:00+07:00, 'value': ...",[],2021-06-22 09:06:39.996000+00:00,47
48,60d1a82016b3330442537223,60d1a81f16b3330442537211,5438574239652778058_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_A,BANNER_STATIC,2589743.50,[5181053909251379448],"[{'date': 2021-02-02 00:00:00+07:00, 'value': ...",[],2021-06-22 09:06:39.997000+00:00,48
49,60d1a82016b3330442537226,60d1a81f16b3330442537211,4638036435127515710_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,4120000.00,[4857469430519615278],[],[],2021-06-22 09:06:39.998000+00:00,49
50,60d1a82016b333044253722c,60d1a81f16b3330442537211,4818379653085429819_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,140000.00,[4827998237552142792],[],[],2021-06-22 09:06:40.001000+00:00,50
51,60d1a82016b3330442537230,60d1a81f16b3330442537211,4943071185361192679_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,4240000.00,[5023173597424371233],[],[],2021-06-22 09:06:40.002000+00:00,51
52,60d1a82016b333044253723a,60d1a81f16b3330442537211,5152950634416065152_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,4180000.00,[5538742900884010760],[],[],2021-06-22 09:06:40.007000+00:00,52

Lấy ngày bắt đầu nhỏ nhất của các campaign và số ngày chạy của problem:

In [30]:
start_date = min(df_campaigns['startDate'])
total_days = PreprocessConverter._get_running_days(df_campaigns)

Dựa vào date int mapper ở dưới, cell dưới đây sẽ: 
* thêm cột `startInt` và `expiredInt` vào data frame, 2 cột này là ngày bắt đầu và kết thúc của campaign nhưng đã được map sang số tự nhiên qua `date_int_mapper` ở bước 1.
* chuyển ngày trong cột `weight` về dạng số tự nhiên luôn
* Tạo thêm cột `dates` là list có dạng \[ngày bắt đầu campaign, ngày kết thúc campaign\]

In [31]:
df_campaigns = PreprocessConverter._add_int_dates(df_campaigns,date_int_mapper['date_to_int'])
df_campaigns = PreprocessConverter._convert_weight_date_to_int(date_int_mapper, df_campaigns)
df_campaigns['dates'] = PreprocessConverter._get_dates_list(df_campaigns)
df_campaigns

,_id,problemId,campaignId,isNetwork,startDate,expiredDate,priority,type,total,placeIds,weights,profiles,createDate,solve_id,startInt,expiredInt,dates
0,60d1a82016b3330442537212,60d1a81f16b3330442537211,4768939651732014836_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.991000+00:00,0,0,100,"[0, 100]"
1,60d1a82016b3330442537213,60d1a81f16b3330442537211,4768939651732014836_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.992000+00:00,1,0,100,"[0, 100]"
2,60d1a82016b3330442537214,60d1a81f16b3330442537211,4810238136557669178_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.992000+00:00,2,0,100,"[0, 100]"
3,60d1a82016b3330442537215,60d1a81f16b3330442537211,4810238136557669178_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.992000+00:00,3,0,100,"[0, 100]"
4,60d1a82016b3330442537216,60d1a81f16b3330442537211,5247609002361599862_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.993000+00:00,4,0,100,"[0, 100]"
5,60d1a82016b3330442537217,60d1a81f16b3330442537211,5247609002361599862_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.993000+00:00,5,0,100,"[0, 100]"
6,60d1a82016b3330442537218,60d1a81f16b3330442537211,5275363820481263653_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.993000+00:00,6,0,100,"[0, 100]"
7,60d1a82016b3330442537219,60d1a81f16b3330442537211,5275363820481263653_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.994000+00:00,7,0,100,"[0, 100]"
8,60d1a82016b333044253721a,60d1a81f16b3330442537211,5322575190744422716_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,166924.75,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},[],2021-06-22 09:06:39.994000+00:00,8,0,100,"[0, 100]"
9,60d1a82016b333044253721b,60d1a81f16b3330442537211,5322575190744422716_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,19235.00,[5181053909251379448],{'-140': 20.0},[],2021-06-22 09:06:39.994000+00:00,9,0,100,"[0, 100]"
10,60d1a82016b333044253721c,60d1a81f16b3330442537211,5370791925364426073_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},[],2021-06-22 09:06:39.995000+00:00,10,0,100,"[0, 100]"
11,60d1a82016b333044253721d,60d1a81f16b3330442537211,5370791925364426073_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{'-140': 20.0},[],2021-06-22 09:06:39.995000+00:00,11,0,100,"[0, 100]"
12,60d1a82016b333044253721e,60d1a81f16b3330442537211,5387657435205013825_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.995000+00:00,12,0,100,"[0, 100]"
13,60d1a82016b333044253721f,60d1a81f16b3330442537211,5387657435205013825_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.996000+00:00,13,0,100,"[0, 100]"
14,60d1a82016b3330442537220,60d1a81f16b3330442537211,5400965728863573515_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.996000+00:00,14,0,100,"[0, 100]"
15,60d1a82016b3330442537221,60d1a81f16b3330442537211,5400965728863573515_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.996000+00:00,15,0,100,"[0, 100]"
16,60d1a82016b3330442537224,60d1a81f16b3330442537211,5577398347147938092_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.997000+00:00,16,0,100,"[0, 100]"
17,60d1a82016b3330442537225,60d1a81f16b3330442537211,5577398347147938092_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.997000+00:00,17,0,100,"[0, 100]"
18,60d1a82016b3330442537227,60d1a81f16b3330442537211,4650504253994331355_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,2589239.00,[4857469430519615278],{},[],2021-06-22 09:06:39.998000+00:00,18,0,66,"[0, 66]"
19,60d1a82016b3330442537228,60d1a81f16b3330442537211,4713760987931352697_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,4240000.00,[5023173597424371233],{},[],2021-06-22 09:06:39.998000+00:00,19,0,66,"[0, 66]"
20,60d1a82016b3330442537229,60d1a81f16b3330442537211,4718198705721931407_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.999000+00:00,20,0,100,"[0, 100]"
21,60d1a82016b333044253722a,60d1a81f16b3330442537211,4741325520555630568_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40+00:00,21,0,100,"[0, 100]"
22,60d1a82016b333044253722b,60d1a81f16b3330442537211,4796633772157943273_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.001000+00:00,22,0,100,"[0, 100]"
23,60d1a82016b333044253722d,60d1a81f16b3330442537211,4823653667180754890_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,1229684.00,[5538742900884010760],{},[],2021-06-22 09:06:40.001000+00:00,23,0,66,"[0, 66]"
24,60d1a82016b333044253722e,60d1a81f16b3330442537211,4824859557802329616_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.002000+00:00,24,0,100,"[0, 100]"
25,60d1a82016b333044253722f,60d1a81f16b3330442537211,4904151939315150524_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.002000+00:00,25,0,100,"[0, 100]"
26,60d1a82016b3330442537231,60d1a81f16b3330442537211,4987628296907052401_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.003000+00:00,26,0,100,"[0, 100]"
27,60d1a82016b3330442537232,60d1a81f16b3330442537211,5004060173322688003_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.003000+00:00,27,0,100,"[0, 100]"
28,60d1a82016b3330442537233,60d1a81f16b3330442537211,5005141348821177586_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.004000+00:00,28,0,100,"[0, 100]"
29,60d1a82016b3330442537234,60d1a81f16b3330442537211,5008562159266208975_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.004000+00:00,29,0,100,"[0, 100]"
30,60d1a82016b3330442537235,60d1a81f16b3330442537211,5112510634931261580_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.005000+00:00,30,0,100,"[0, 100]"
31,60d1a82016b3330442537236,60d1a81f16b3330442537211,5116176280026807920_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.005000+00:00,31,0,100,"[0, 100]"
32,60d1a82016b3330442537237,60d1a81f16b3330442537211,5140955443670820219_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.005000+00:00,32,0,100,"[0, 100]"
33,60d1a82016b3330442537238,60d1a81f16b3330442537211,5144070500760291817_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.006000+00:00,33,0,100,"[0, 100]"
34,60d1a82016b3330442537239,60d1a81f16b3330442537211,5145360317263062170_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,163588.39,[4827998237552142792],{},[],2021-06-22 09:06:40.006000+00:00,34,0,66,"[0, 66]"
35,60d1a82016b333044253723b,60d1a81f16b3330442537211,5261690011954745524_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.007000+00:00,35,0,100,"[0, 100]"
36,60d1a82016b333044253723c,60d1a81f16b3330442537211,5326884055688590955_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,1118869.00,[5023173597424371233],{},[],2021-06-22 09:06:40.007000+00:00,36,0,66,"[0, 66]"
37,60d1a82016b333044253723d,60d1a81f16b3330442537211,5349652368050952557_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,4120000.00,[4857469430519615278],{},[],2021-06-22 09:06:40.008000+00:00,37,0,66,"[0, 66]"
38,60d1a82016b333044253723e,60d1a81f16b3330442537211,5351581853241914431_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.008000+00:00,38,0,100,"[0, 100]"
39,60d1a82016b333044253723f,60d1a81f16b3330442537211,5430288141589897773_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.008000+00:00,39,0,100,"[0, 100]"
40,60d1a82016b3330442537240,60d1a81f16b3330442537211,5447298725065630394_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.009000+00:00,40,0,100,"[0, 100]"
41,60d1a82016b3330442537241,60d1a81f16b3330442537211,5471706532034127453_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,4180000.00,[5538742900884010760],{},[],2021-06-22 09:06:40.009000+00:00,41,0,66,"[0, 66]"
42,60d1a82016b3330442537242,60d1a81f16b3330442537211,5596899021949443719_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,140000.00,[4827998237552142792],{},[],2021-06-22 09:06:40.010000+00:00,42,0,66,"[0, 66]"
43,60d1a82016b3330442537243,60d1a81f16b3330442537211,5609987844990570937_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.010000+00:00,43,0,100,"[0, 100]"
44,60d1a82016b3330442537244,60d1a81f16b3330442537211,5646870611503620553_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.011000+00:00,44,0,100,"[0, 100]"
45,60d1a82016b3330442537245,60d1a81f16b3330442537211,5678313728368360859_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.011000+00:00,45,0,100,"[0, 100]"
46,60d1a82016b3330442537246,60d1a81f16b3330442537211,5740071104871774323_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.012000+00:00,46,0,100,"[0, 100]"
47,60d1a82016b3330442537222,60d1a81f16b3330442537211,5438574239652778058_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_A,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},[],2021-06-22 09:06:39.996000+00:00,47,0,100,"[0, 100]"
48,60d1a82016b3330442537223,60d1a81f16b3330442537211,5438574239652778058_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_A,BANNER_STATIC,2589743.50,[5181053909251379448],{'-140': 20.0},[],2021-06-22 09:06:39.997000+00:00,48,0,100,"[0, 100]"
49,60d1a82016b3330442537226,60d1a81f16b3330442537211,4638036435127515710_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,4120000.00,[4857469430519615278],{},[],2021-06-22 09:06:39.998000+00:00,49,0,66,"[0, 66]"
50,60d1a82016b333044253722c,60d1a81f16b3330442537211,4818379653085429819_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,140000.00,[4827998237552142792],{},[],2021-06-22 09:06:40.001000+00:00,50,0,66,"[0, 66]"
51,60d1a82016b3330442537230,60d1a81f16b3330442537211,4943071185361192679_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,4240000.00,[5023173597424371233],{},[],2021-06-22 09:06:40.002000+00:00,51,0,66,"[0, 66]"
52,60d1a82016b333044253723a,60d1a81f16b3330442537211,5152950634416065152_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,4180000.00,[5538742900884010760],{},[],2021-06-22 09:06:40.007000+00:00,52,0,66,"[0, 66]"

Đổi tên các thứ:

In [32]:
df_campaigns.rename(columns = {'campaignId': 'original_id', 'cType': 'type', 'placeIds': 'place_ids'},inplace= True)
df_campaigns

,_id,problemId,original_id,isNetwork,startDate,expiredDate,priority,type,total,place_ids,weights,profiles,createDate,solve_id,startInt,expiredInt,dates
0,60d1a82016b3330442537212,60d1a81f16b3330442537211,4768939651732014836_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.991000+00:00,0,0,100,"[0, 100]"
1,60d1a82016b3330442537213,60d1a81f16b3330442537211,4768939651732014836_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.992000+00:00,1,0,100,"[0, 100]"
2,60d1a82016b3330442537214,60d1a81f16b3330442537211,4810238136557669178_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.992000+00:00,2,0,100,"[0, 100]"
3,60d1a82016b3330442537215,60d1a81f16b3330442537211,4810238136557669178_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.992000+00:00,3,0,100,"[0, 100]"
4,60d1a82016b3330442537216,60d1a81f16b3330442537211,5247609002361599862_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.993000+00:00,4,0,100,"[0, 100]"
5,60d1a82016b3330442537217,60d1a81f16b3330442537211,5247609002361599862_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.993000+00:00,5,0,100,"[0, 100]"
6,60d1a82016b3330442537218,60d1a81f16b3330442537211,5275363820481263653_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.993000+00:00,6,0,100,"[0, 100]"
7,60d1a82016b3330442537219,60d1a81f16b3330442537211,5275363820481263653_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.994000+00:00,7,0,100,"[0, 100]"
8,60d1a82016b333044253721a,60d1a81f16b3330442537211,5322575190744422716_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,166924.75,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},[],2021-06-22 09:06:39.994000+00:00,8,0,100,"[0, 100]"
9,60d1a82016b333044253721b,60d1a81f16b3330442537211,5322575190744422716_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,19235.00,[5181053909251379448],{'-140': 20.0},[],2021-06-22 09:06:39.994000+00:00,9,0,100,"[0, 100]"
10,60d1a82016b333044253721c,60d1a81f16b3330442537211,5370791925364426073_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},[],2021-06-22 09:06:39.995000+00:00,10,0,100,"[0, 100]"
11,60d1a82016b333044253721d,60d1a81f16b3330442537211,5370791925364426073_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{'-140': 20.0},[],2021-06-22 09:06:39.995000+00:00,11,0,100,"[0, 100]"
12,60d1a82016b333044253721e,60d1a81f16b3330442537211,5387657435205013825_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.995000+00:00,12,0,100,"[0, 100]"
13,60d1a82016b333044253721f,60d1a81f16b3330442537211,5387657435205013825_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.996000+00:00,13,0,100,"[0, 100]"
14,60d1a82016b3330442537220,60d1a81f16b3330442537211,5400965728863573515_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.996000+00:00,14,0,100,"[0, 100]"
15,60d1a82016b3330442537221,60d1a81f16b3330442537211,5400965728863573515_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.996000+00:00,15,0,100,"[0, 100]"
16,60d1a82016b3330442537224,60d1a81f16b3330442537211,5577398347147938092_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.997000+00:00,16,0,100,"[0, 100]"
17,60d1a82016b3330442537225,60d1a81f16b3330442537211,5577398347147938092_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.997000+00:00,17,0,100,"[0, 100]"
18,60d1a82016b3330442537227,60d1a81f16b3330442537211,4650504253994331355_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,2589239.00,[4857469430519615278],{},[],2021-06-22 09:06:39.998000+00:00,18,0,66,"[0, 66]"
19,60d1a82016b3330442537228,60d1a81f16b3330442537211,4713760987931352697_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,4240000.00,[5023173597424371233],{},[],2021-06-22 09:06:39.998000+00:00,19,0,66,"[0, 66]"
20,60d1a82016b3330442537229,60d1a81f16b3330442537211,4718198705721931407_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:39.999000+00:00,20,0,100,"[0, 100]"
21,60d1a82016b333044253722a,60d1a81f16b3330442537211,4741325520555630568_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40+00:00,21,0,100,"[0, 100]"
22,60d1a82016b333044253722b,60d1a81f16b3330442537211,4796633772157943273_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.001000+00:00,22,0,100,"[0, 100]"
23,60d1a82016b333044253722d,60d1a81f16b3330442537211,4823653667180754890_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,1229684.00,[5538742900884010760],{},[],2021-06-22 09:06:40.001000+00:00,23,0,66,"[0, 66]"
24,60d1a82016b333044253722e,60d1a81f16b3330442537211,4824859557802329616_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.002000+00:00,24,0,100,"[0, 100]"
25,60d1a82016b333044253722f,60d1a81f16b3330442537211,4904151939315150524_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.002000+00:00,25,0,100,"[0, 100]"
26,60d1a82016b3330442537231,60d1a81f16b3330442537211,4987628296907052401_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.003000+00:00,26,0,100,"[0, 100]"
27,60d1a82016b3330442537232,60d1a81f16b3330442537211,5004060173322688003_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.003000+00:00,27,0,100,"[0, 100]"
28,60d1a82016b3330442537233,60d1a81f16b3330442537211,5005141348821177586_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.004000+00:00,28,0,100,"[0, 100]"
29,60d1a82016b3330442537234,60d1a81f16b3330442537211,5008562159266208975_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.004000+00:00,29,0,100,"[0, 100]"
30,60d1a82016b3330442537235,60d1a81f16b3330442537211,5112510634931261580_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.005000+00:00,30,0,100,"[0, 100]"
31,60d1a82016b3330442537236,60d1a81f16b3330442537211,5116176280026807920_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.005000+00:00,31,0,100,"[0, 100]"
32,60d1a82016b3330442537237,60d1a81f16b3330442537211,5140955443670820219_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.005000+00:00,32,0,100,"[0, 100]"
33,60d1a82016b3330442537238,60d1a81f16b3330442537211,5144070500760291817_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.006000+00:00,33,0,100,"[0, 100]"
34,60d1a82016b3330442537239,60d1a81f16b3330442537211,5145360317263062170_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,163588.39,[4827998237552142792],{},[],2021-06-22 09:06:40.006000+00:00,34,0,66,"[0, 66]"
35,60d1a82016b333044253723b,60d1a81f16b3330442537211,5261690011954745524_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.007000+00:00,35,0,100,"[0, 100]"
36,60d1a82016b333044253723c,60d1a81f16b3330442537211,5326884055688590955_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,1118869.00,[5023173597424371233],{},[],2021-06-22 09:06:40.007000+00:00,36,0,66,"[0, 66]"
37,60d1a82016b333044253723d,60d1a81f16b3330442537211,5349652368050952557_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,4120000.00,[4857469430519615278],{},[],2021-06-22 09:06:40.008000+00:00,37,0,66,"[0, 66]"
38,60d1a82016b333044253723e,60d1a81f16b3330442537211,5351581853241914431_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.008000+00:00,38,0,100,"[0, 100]"
39,60d1a82016b333044253723f,60d1a81f16b3330442537211,5430288141589897773_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.008000+00:00,39,0,100,"[0, 100]"
40,60d1a82016b3330442537240,60d1a81f16b3330442537211,5447298725065630394_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.009000+00:00,40,0,100,"[0, 100]"
41,60d1a82016b3330442537241,60d1a81f16b3330442537211,5471706532034127453_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,4180000.00,[5538742900884010760],{},[],2021-06-22 09:06:40.009000+00:00,41,0,66,"[0, 66]"
42,60d1a82016b3330442537242,60d1a81f16b3330442537211,5596899021949443719_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,140000.00,[4827998237552142792],{},[],2021-06-22 09:06:40.010000+00:00,42,0,66,"[0, 66]"
43,60d1a82016b3330442537243,60d1a81f16b3330442537211,5609987844990570937_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.010000+00:00,43,0,100,"[0, 100]"
44,60d1a82016b3330442537244,60d1a81f16b3330442537211,5646870611503620553_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},"[[{'values': [1], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.011000+00:00,44,0,100,"[0, 100]"
45,60d1a82016b3330442537245,60d1a81f16b3330442537211,5678313728368360859_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.011000+00:00,45,0,100,"[0, 100]"
46,60d1a82016b3330442537246,60d1a81f16b3330442537211,5740071104871774323_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},"[[{'values': [0], 'type': 'GENDER'}, {'type': ...",2021-06-22 09:06:40.012000+00:00,46,0,100,"[0, 100]"
47,60d1a82016b3330442537222,60d1a81f16b3330442537211,5438574239652778058_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_A,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},[],2021-06-22 09:06:39.996000+00:00,47,0,100,"[0, 100]"
48,60d1a82016b3330442537223,60d1a81f16b3330442537211,5438574239652778058_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_A,BANNER_STATIC,2589743.50,[5181053909251379448],{'-140': 20.0},[],2021-06-22 09:06:39.997000+00:00,48,0,100,"[0, 100]"
49,60d1a82016b3330442537226,60d1a81f16b3330442537211,4638036435127515710_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,4120000.00,[4857469430519615278],{},[],2021-06-22 09:06:39.998000+00:00,49,0,66,"[0, 66]"
50,60d1a82016b333044253722c,60d1a81f16b3330442537211,4818379653085429819_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,140000.00,[4827998237552142792],{},[],2021-06-22 09:06:40.001000+00:00,50,0,66,"[0, 66]"
51,60d1a82016b3330442537230,60d1a81f16b3330442537211,4943071185361192679_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,4240000.00,[5023173597424371233],{},[],2021-06-22 09:06:40.002000+00:00,51,0,66,"[0, 66]"
52,60d1a82016b333044253723a,60d1a81f16b3330442537211,5152950634416065152_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,4180000.00,[5538742900884010760],{},[],2021-06-22 09:06:40.007000+00:00,52,0,66,"[0, 66]"

Đổi giá trị cột `profiles` thành đối tượng `CampaignProfile`, tương tự như `PlaceProfile`, `CampaignProfile` cũng có 3 dạng `db_rep`, `list_rep`, `int_rep`

In [33]:
df_campaigns['profiles'] = [CampaignProfile(profile_db_rep) for profile_db_rep in df_campaigns['profiles']]
df_campaigns

,_id,problemId,original_id,isNetwork,startDate,expiredDate,priority,type,total,place_ids,weights,profiles,createDate,solve_id,startInt,expiredInt,dates
0,60d1a82016b3330442537212,60d1a81f16b3330442537211,4768939651732014836_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.991000+00:00,0,0,100,"[0, 100]"
1,60d1a82016b3330442537213,60d1a81f16b3330442537211,4768939651732014836_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.992000+00:00,1,0,100,"[0, 100]"
2,60d1a82016b3330442537214,60d1a81f16b3330442537211,4810238136557669178_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.992000+00:00,2,0,100,"[0, 100]"
3,60d1a82016b3330442537215,60d1a81f16b3330442537211,4810238136557669178_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.992000+00:00,3,0,100,"[0, 100]"
4,60d1a82016b3330442537216,60d1a81f16b3330442537211,5247609002361599862_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.993000+00:00,4,0,100,"[0, 100]"
5,60d1a82016b3330442537217,60d1a81f16b3330442537211,5247609002361599862_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.993000+00:00,5,0,100,"[0, 100]"
6,60d1a82016b3330442537218,60d1a81f16b3330442537211,5275363820481263653_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.993000+00:00,6,0,100,"[0, 100]"
7,60d1a82016b3330442537219,60d1a81f16b3330442537211,5275363820481263653_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.994000+00:00,7,0,100,"[0, 100]"
8,60d1a82016b333044253721a,60d1a81f16b3330442537211,5322575190744422716_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,166924.75,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.994000+00:00,8,0,100,"[0, 100]"
9,60d1a82016b333044253721b,60d1a81f16b3330442537211,5322575190744422716_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,19235.00,[5181053909251379448],{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.994000+00:00,9,0,100,"[0, 100]"
10,60d1a82016b333044253721c,60d1a81f16b3330442537211,5370791925364426073_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.995000+00:00,10,0,100,"[0, 100]"
11,60d1a82016b333044253721d,60d1a81f16b3330442537211,5370791925364426073_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.995000+00:00,11,0,100,"[0, 100]"
12,60d1a82016b333044253721e,60d1a81f16b3330442537211,5387657435205013825_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.995000+00:00,12,0,100,"[0, 100]"
13,60d1a82016b333044253721f,60d1a81f16b3330442537211,5387657435205013825_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,13,0,100,"[0, 100]"
14,60d1a82016b3330442537220,60d1a81f16b3330442537211,5400965728863573515_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,14,0,100,"[0, 100]"
15,60d1a82016b3330442537221,60d1a81f16b3330442537211,5400965728863573515_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,15,0,100,"[0, 100]"
16,60d1a82016b3330442537224,60d1a81f16b3330442537211,5577398347147938092_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.997000+00:00,16,0,100,"[0, 100]"
17,60d1a82016b3330442537225,60d1a81f16b3330442537211,5577398347147938092_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.997000+00:00,17,0,100,"[0, 100]"
18,60d1a82016b3330442537227,60d1a81f16b3330442537211,4650504253994331355_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,2589239.00,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.998000+00:00,18,0,66,"[0, 66]"
19,60d1a82016b3330442537228,60d1a81f16b3330442537211,4713760987931352697_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,4240000.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.998000+00:00,19,0,66,"[0, 66]"
20,60d1a82016b3330442537229,60d1a81f16b3330442537211,4718198705721931407_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.999000+00:00,20,0,100,"[0, 100]"
21,60d1a82016b333044253722a,60d1a81f16b3330442537211,4741325520555630568_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40+00:00,21,0,100,"[0, 100]"
22,60d1a82016b333044253722b,60d1a81f16b3330442537211,4796633772157943273_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.001000+00:00,22,0,100,"[0, 100]"
23,60d1a82016b333044253722d,60d1a81f16b3330442537211,4823653667180754890_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,1229684.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.001000+00:00,23,0,66,"[0, 66]"
24,60d1a82016b333044253722e,60d1a81f16b3330442537211,4824859557802329616_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.002000+00:00,24,0,100,"[0, 100]"
25,60d1a82016b333044253722f,60d1a81f16b3330442537211,4904151939315150524_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.002000+00:00,25,0,100,"[0, 100]"
26,60d1a82016b3330442537231,60d1a81f16b3330442537211,4987628296907052401_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.003000+00:00,26,0,100,"[0, 100]"
27,60d1a82016b3330442537232,60d1a81f16b3330442537211,5004060173322688003_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.003000+00:00,27,0,100,"[0, 100]"
28,60d1a82016b3330442537233,60d1a81f16b3330442537211,5005141348821177586_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.004000+00:00,28,0,100,"[0, 100]"
29,60d1a82016b3330442537234,60d1a81f16b3330442537211,5008562159266208975_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.004000+00:00,29,0,100,"[0, 100]"
30,60d1a82016b3330442537235,60d1a81f16b3330442537211,5112510634931261580_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.005000+00:00,30,0,100,"[0, 100]"
31,60d1a82016b3330442537236,60d1a81f16b3330442537211,5116176280026807920_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.005000+00:00,31,0,100,"[0, 100]"
32,60d1a82016b3330442537237,60d1a81f16b3330442537211,5140955443670820219_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.005000+00:00,32,0,100,"[0, 100]"
33,60d1a82016b3330442537238,60d1a81f16b3330442537211,5144070500760291817_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.006000+00:00,33,0,100,"[0, 100]"
34,60d1a82016b3330442537239,60d1a81f16b3330442537211,5145360317263062170_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,163588.39,[4827998237552142792],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.006000+00:00,34,0,66,"[0, 66]"
35,60d1a82016b333044253723b,60d1a81f16b3330442537211,5261690011954745524_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.007000+00:00,35,0,100,"[0, 100]"
36,60d1a82016b333044253723c,60d1a81f16b3330442537211,5326884055688590955_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,1118869.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.007000+00:00,36,0,66,"[0, 66]"
37,60d1a82016b333044253723d,60d1a81f16b3330442537211,5349652368050952557_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,4120000.00,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.008000+00:00,37,0,66,"[0, 66]"
38,60d1a82016b333044253723e,60d1a81f16b3330442537211,5351581853241914431_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.008000+00:00,38,0,100,"[0, 100]"
39,60d1a82016b333044253723f,60d1a81f16b3330442537211,5430288141589897773_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.008000+00:00,39,0,100,"[0, 100]"
40,60d1a82016b3330442537240,60d1a81f16b3330442537211,5447298725065630394_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.009000+00:00,40,0,100,"[0, 100]"
41,60d1a82016b3330442537241,60d1a81f16b3330442537211,5471706532034127453_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,4180000.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.009000+00:00,41,0,66,"[0, 66]"
42,60d1a82016b3330442537242,60d1a81f16b3330442537211,5596899021949443719_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,140000.00,[4827998237552142792],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.010000+00:00,42,0,66,"[0, 66]"
43,60d1a82016b3330442537243,60d1a81f16b3330442537211,5609987844990570937_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.010000+00:00,43,0,100,"[0, 100]"
44,60d1a82016b3330442537244,60d1a81f16b3330442537211,5646870611503620553_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.011000+00:00,44,0,100,"[0, 100]"
45,60d1a82016b3330442537245,60d1a81f16b3330442537211,5678313728368360859_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.011000+00:00,45,0,100,"[0, 100]"
46,60d1a82016b3330442537246,60d1a81f16b3330442537211,5740071104871774323_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.012000+00:00,46,0,100,"[0, 100]"
47,60d1a82016b3330442537222,60d1a81f16b3330442537211,5438574239652778058_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_A,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,47,0,100,"[0, 100]"
48,60d1a82016b3330442537223,60d1a81f16b3330442537211,5438574239652778058_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_A,BANNER_STATIC,2589743.50,[5181053909251379448],{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.997000+00:00,48,0,100,"[0, 100]"
49,60d1a82016b3330442537226,60d1a81f16b3330442537211,4638036435127515710_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,4120000.00,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.998000+00:00,49,0,66,"[0, 66]"
50,60d1a82016b333044253722c,60d1a81f16b3330442537211,4818379653085429819_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,140000.00,[4827998237552142792],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.001000+00:00,50,0,66,"[0, 66]"
51,60d1a82016b3330442537230,60d1a81f16b3330442537211,4943071185361192679_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,4240000.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.002000+00:00,51,0,66,"[0, 66]"
52,60d1a82016b333044253723a,60d1a81f16b3330442537211,5152950634416065152_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,4180000.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.007000+00:00,52,0,66,"[0, 66]"

Thêm cột `solve_place_ids` là solve id của place tương mà từng campaign chạy

In [34]:
preprocessed_places = df_places
df_campaigns = PreprocessConverter._add_solve_place_ids(df_campaigns, preprocessed_places)
df_campaigns

,_id,problemId,original_id,isNetwork,startDate,expiredDate,priority,type,total,place_ids,weights,profiles,createDate,solve_id,startInt,expiredInt,dates,solve_place_ids
0,60d1a82016b3330442537212,60d1a81f16b3330442537211,4768939651732014836_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.991000+00:00,0,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
1,60d1a82016b3330442537213,60d1a81f16b3330442537211,4768939651732014836_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.992000+00:00,1,0,100,"[0, 100]",[7]
2,60d1a82016b3330442537214,60d1a81f16b3330442537211,4810238136557669178_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.992000+00:00,2,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
3,60d1a82016b3330442537215,60d1a81f16b3330442537211,4810238136557669178_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.992000+00:00,3,0,100,"[0, 100]",[7]
4,60d1a82016b3330442537216,60d1a81f16b3330442537211,5247609002361599862_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.993000+00:00,4,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
5,60d1a82016b3330442537217,60d1a81f16b3330442537211,5247609002361599862_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.993000+00:00,5,0,100,"[0, 100]",[7]
6,60d1a82016b3330442537218,60d1a81f16b3330442537211,5275363820481263653_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.993000+00:00,6,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
7,60d1a82016b3330442537219,60d1a81f16b3330442537211,5275363820481263653_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.994000+00:00,7,0,100,"[0, 100]",[7]
8,60d1a82016b333044253721a,60d1a81f16b3330442537211,5322575190744422716_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,166924.75,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.994000+00:00,8,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
9,60d1a82016b333044253721b,60d1a81f16b3330442537211,5322575190744422716_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,19235.00,[5181053909251379448],{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.994000+00:00,9,0,100,"[0, 100]",[7]
10,60d1a82016b333044253721c,60d1a81f16b3330442537211,5370791925364426073_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.995000+00:00,10,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
11,60d1a82016b333044253721d,60d1a81f16b3330442537211,5370791925364426073_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.995000+00:00,11,0,100,"[0, 100]",[7]
12,60d1a82016b333044253721e,60d1a81f16b3330442537211,5387657435205013825_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.995000+00:00,12,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
13,60d1a82016b333044253721f,60d1a81f16b3330442537211,5387657435205013825_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,13,0,100,"[0, 100]",[7]
14,60d1a82016b3330442537220,60d1a81f16b3330442537211,5400965728863573515_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,14,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
15,60d1a82016b3330442537221,60d1a81f16b3330442537211,5400965728863573515_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,15,0,100,"[0, 100]",[7]
16,60d1a82016b3330442537224,60d1a81f16b3330442537211,5577398347147938092_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.997000+00:00,16,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
17,60d1a82016b3330442537225,60d1a81f16b3330442537211,5577398347147938092_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,BANNER_STATIC,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.997000+00:00,17,0,100,"[0, 100]",[7]
18,60d1a82016b3330442537227,60d1a81f16b3330442537211,4650504253994331355_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,2589239.00,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.998000+00:00,18,0,66,"[0, 66]",[1]
19,60d1a82016b3330442537228,60d1a81f16b3330442537211,4713760987931352697_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,4240000.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.998000+00:00,19,0,66,"[0, 66]",[5]
20,60d1a82016b3330442537229,60d1a81f16b3330442537211,4718198705721931407_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.999000+00:00,20,0,100,"[0, 100]",[5]
21,60d1a82016b333044253722a,60d1a81f16b3330442537211,4741325520555630568_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40+00:00,21,0,100,"[0, 100]",[2]
22,60d1a82016b333044253722b,60d1a81f16b3330442537211,4796633772157943273_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.001000+00:00,22,0,100,"[0, 100]",[2]
23,60d1a82016b333044253722d,60d1a81f16b3330442537211,4823653667180754890_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,1229684.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.001000+00:00,23,0,66,"[0, 66]",[2]
24,60d1a82016b333044253722e,60d1a81f16b3330442537211,4824859557802329616_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.002000+00:00,24,0,100,"[0, 100]",[1]
25,60d1a82016b333044253722f,60d1a81f16b3330442537211,4904151939315150524_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.002000+00:00,25,0,100,"[0, 100]",[1]
26,60d1a82016b3330442537231,60d1a81f16b3330442537211,4987628296907052401_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.003000+00:00,26,0,100,"[0, 100]",[5]
27,60d1a82016b3330442537232,60d1a81f16b3330442537211,5004060173322688003_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.003000+00:00,27,0,100,"[0, 100]",[5]
28,60d1a82016b3330442537233,60d1a81f16b3330442537211,5005141348821177586_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.004000+00:00,28,0,100,"[0, 100]",[2]
29,60d1a82016b3330442537234,60d1a81f16b3330442537211,5008562159266208975_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.004000+00:00,29,0,100,"[0, 100]",[1]
30,60d1a82016b3330442537235,60d1a81f16b3330442537211,5112510634931261580_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.005000+00:00,30,0,100,"[0, 100]",[1]
31,60d1a82016b3330442537236,60d1a81f16b3330442537211,5116176280026807920_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.005000+00:00,31,0,100,"[0, 100]",[1]
32,60d1a82016b3330442537237,60d1a81f16b3330442537211,5140955443670820219_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.005000+00:00,32,0,100,"[0, 100]",[2]
33,60d1a82016b3330442537238,60d1a81f16b3330442537211,5144070500760291817_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.006000+00:00,33,0,100,"[0, 100]",[5]
34,60d1a82016b3330442537239,60d1a81f16b3330442537211,5145360317263062170_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,163588.39,[4827998237552142792],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.006000+00:00,34,0,66,"[0, 66]",[0]
35,60d1a82016b333044253723b,60d1a81f16b3330442537211,5261690011954745524_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.007000+00:00,35,0,100,"[0, 100]",[5]
36,60d1a82016b333044253723c,60d1a81f16b3330442537211,5326884055688590955_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,1118869.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.007000+00:00,36,0,66,"[0, 66]",[5]
37,60d1a82016b333044253723d,60d1a81f16b3330442537211,5349652368050952557_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,4120000.00,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.008000+00:00,37,0,66,"[0, 66]",[1]
38,60d1a82016b333044253723e,60d1a81f16b3330442537211,5351581853241914431_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.008000+00:00,38,0,100,"[0, 100]",[1]
39,60d1a82016b333044253723f,60d1a81f16b3330442537211,5430288141589897773_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.008000+00:00,39,0,100,"[0, 100]",[2]
40,60d1a82016b3330442537240,60d1a81f16b3330442537211,5447298725065630394_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.009000+00:00,40,0,100,"[0, 100]",[5]
41,60d1a82016b3330442537241,60d1a81f16b3330442537211,5471706532034127453_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,4180000.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.009000+00:00,41,0,66,"[0, 66]",[2]
42,60d1a82016b3330442537242,60d1a81f16b3330442537211,5596899021949443719_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,DEFAULT,140000.00,[4827998237552142792],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.010000+00:00,42,0,66,"[0, 66]",[0]
43,60d1a82016b3330442537243,60d1a81f16b3330442537211,5609987844990570937_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.010000+00:00,43,0,100,"[0, 100]",[5]
44,60d1a82016b3330442537244,60d1a81f16b3330442537211,5646870611503620553_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.011000+00:00,44,0,100,"[0, 100]",[2]
45,60d1a82016b3330442537245,60d1a81f16b3330442537211,5678313728368360859_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.011000+00:00,45,0,100,"[0, 100]",[2]
46,60d1a82016b3330442537246,60d1a81f16b3330442537211,5740071104871774323_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,DEFAULT,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.012000+00:00,46,0,100,"[0, 100]",[1]
47,60d1a82016b3330442537222,60d1a81f16b3330442537211,5438574239652778058_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_A,BANNER_STATIC,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,47,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
48,60d1a82016b3330442537223,60d1a81f16b3330442537211,5438574239652778058_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_A,BANNER_STATIC,2589743.50,[5181053909251379448],{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.997000+00:00,48,0,100,"[0, 100]",[7]
49,60d1a82016b3330442537226,60d1a81f16b3330442537211,4638036435127515710_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,4120000.00,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.998000+00:00,49,0,66,"[0, 66]",[1]
50,60d1a82016b333044253722c,60d1a81f16b3330442537211,4818379653085429819_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,140000.00,[4827998237552142792],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.001000+00:00,50,0,66,"[0, 66]",[0]
51,60d1a82016b3330442537230,60d1a81f16b3330442537211,4943071185361192679_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,4240000.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.002000+00:00,51,0,66,"[0, 66]",[5]
52,60d1a82016b333044253723a,60d1a81f16b3330442537211,5152950634416065152_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,DEFAULT,4180000.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.007000+00:00,52,0,66,"[0, 66]",[2]

Đổi campaign type sang int tương ứng

In [35]:
df_campaigns['type'] = df_campaigns['type'].apply(lambda x: acm_base_pb2.CampaignType.Value(x))
df_campaigns

,_id,problemId,original_id,isNetwork,startDate,expiredDate,priority,type,total,place_ids,weights,profiles,createDate,solve_id,startInt,expiredInt,dates,solve_place_ids
0,60d1a82016b3330442537212,60d1a81f16b3330442537211,4768939651732014836_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,1,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.991000+00:00,0,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
1,60d1a82016b3330442537213,60d1a81f16b3330442537211,4768939651732014836_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,1,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.992000+00:00,1,0,100,"[0, 100]",[7]
2,60d1a82016b3330442537214,60d1a81f16b3330442537211,4810238136557669178_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,1,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.992000+00:00,2,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
3,60d1a82016b3330442537215,60d1a81f16b3330442537211,4810238136557669178_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,1,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.992000+00:00,3,0,100,"[0, 100]",[7]
4,60d1a82016b3330442537216,60d1a81f16b3330442537211,5247609002361599862_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,1,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.993000+00:00,4,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
5,60d1a82016b3330442537217,60d1a81f16b3330442537211,5247609002361599862_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,1,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.993000+00:00,5,0,100,"[0, 100]",[7]
6,60d1a82016b3330442537218,60d1a81f16b3330442537211,5275363820481263653_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,1,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.993000+00:00,6,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
7,60d1a82016b3330442537219,60d1a81f16b3330442537211,5275363820481263653_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,1,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.994000+00:00,7,0,100,"[0, 100]",[7]
8,60d1a82016b333044253721a,60d1a81f16b3330442537211,5322575190744422716_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,1,166924.75,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.994000+00:00,8,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
9,60d1a82016b333044253721b,60d1a81f16b3330442537211,5322575190744422716_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,1,19235.00,[5181053909251379448],{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.994000+00:00,9,0,100,"[0, 100]",[7]
10,60d1a82016b333044253721c,60d1a81f16b3330442537211,5370791925364426073_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,1,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.995000+00:00,10,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
11,60d1a82016b333044253721d,60d1a81f16b3330442537211,5370791925364426073_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,1,2589743.50,[5181053909251379448],{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.995000+00:00,11,0,100,"[0, 100]",[7]
12,60d1a82016b333044253721e,60d1a81f16b3330442537211,5387657435205013825_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,1,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.995000+00:00,12,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
13,60d1a82016b333044253721f,60d1a81f16b3330442537211,5387657435205013825_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,1,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,13,0,100,"[0, 100]",[7]
14,60d1a82016b3330442537220,60d1a81f16b3330442537211,5400965728863573515_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,1,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,14,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
15,60d1a82016b3330442537221,60d1a81f16b3330442537211,5400965728863573515_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,1,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,15,0,100,"[0, 100]",[7]
16,60d1a82016b3330442537224,60d1a81f16b3330442537211,5577398347147938092_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,1,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.997000+00:00,16,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
17,60d1a82016b3330442537225,60d1a81f16b3330442537211,5577398347147938092_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,1,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.997000+00:00,17,0,100,"[0, 100]",[7]
18,60d1a82016b3330442537227,60d1a81f16b3330442537211,4650504253994331355_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,0,2589239.00,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.998000+00:00,18,0,66,"[0, 66]",[1]
19,60d1a82016b3330442537228,60d1a81f16b3330442537211,4713760987931352697_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,0,4240000.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.998000+00:00,19,0,66,"[0, 66]",[5]
20,60d1a82016b3330442537229,60d1a81f16b3330442537211,4718198705721931407_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.999000+00:00,20,0,100,"[0, 100]",[5]
21,60d1a82016b333044253722a,60d1a81f16b3330442537211,4741325520555630568_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40+00:00,21,0,100,"[0, 100]",[2]
22,60d1a82016b333044253722b,60d1a81f16b3330442537211,4796633772157943273_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.001000+00:00,22,0,100,"[0, 100]",[2]
23,60d1a82016b333044253722d,60d1a81f16b3330442537211,4823653667180754890_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,0,1229684.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.001000+00:00,23,0,66,"[0, 66]",[2]
24,60d1a82016b333044253722e,60d1a81f16b3330442537211,4824859557802329616_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.002000+00:00,24,0,100,"[0, 100]",[1]
25,60d1a82016b333044253722f,60d1a81f16b3330442537211,4904151939315150524_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.002000+00:00,25,0,100,"[0, 100]",[1]
26,60d1a82016b3330442537231,60d1a81f16b3330442537211,4987628296907052401_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.003000+00:00,26,0,100,"[0, 100]",[5]
27,60d1a82016b3330442537232,60d1a81f16b3330442537211,5004060173322688003_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.003000+00:00,27,0,100,"[0, 100]",[5]
28,60d1a82016b3330442537233,60d1a81f16b3330442537211,5005141348821177586_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.004000+00:00,28,0,100,"[0, 100]",[2]
29,60d1a82016b3330442537234,60d1a81f16b3330442537211,5008562159266208975_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.004000+00:00,29,0,100,"[0, 100]",[1]
30,60d1a82016b3330442537235,60d1a81f16b3330442537211,5112510634931261580_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.005000+00:00,30,0,100,"[0, 100]",[1]
31,60d1a82016b3330442537236,60d1a81f16b3330442537211,5116176280026807920_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.005000+00:00,31,0,100,"[0, 100]",[1]
32,60d1a82016b3330442537237,60d1a81f16b3330442537211,5140955443670820219_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.005000+00:00,32,0,100,"[0, 100]",[2]
33,60d1a82016b3330442537238,60d1a81f16b3330442537211,5144070500760291817_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.006000+00:00,33,0,100,"[0, 100]",[5]
34,60d1a82016b3330442537239,60d1a81f16b3330442537211,5145360317263062170_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,0,163588.39,[4827998237552142792],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.006000+00:00,34,0,66,"[0, 66]",[0]
35,60d1a82016b333044253723b,60d1a81f16b3330442537211,5261690011954745524_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.007000+00:00,35,0,100,"[0, 100]",[5]
36,60d1a82016b333044253723c,60d1a81f16b3330442537211,5326884055688590955_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,0,1118869.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.007000+00:00,36,0,66,"[0, 66]",[5]
37,60d1a82016b333044253723d,60d1a81f16b3330442537211,5349652368050952557_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,0,4120000.00,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.008000+00:00,37,0,66,"[0, 66]",[1]
38,60d1a82016b333044253723e,60d1a81f16b3330442537211,5351581853241914431_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.008000+00:00,38,0,100,"[0, 100]",[1]
39,60d1a82016b333044253723f,60d1a81f16b3330442537211,5430288141589897773_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.008000+00:00,39,0,100,"[0, 100]",[2]
40,60d1a82016b3330442537240,60d1a81f16b3330442537211,5447298725065630394_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.009000+00:00,40,0,100,"[0, 100]",[5]
41,60d1a82016b3330442537241,60d1a81f16b3330442537211,5471706532034127453_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,0,4180000.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.009000+00:00,41,0,66,"[0, 66]",[2]
42,60d1a82016b3330442537242,60d1a81f16b3330442537211,5596899021949443719_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_B,0,140000.00,[4827998237552142792],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.010000+00:00,42,0,66,"[0, 66]",[0]
43,60d1a82016b3330442537243,60d1a81f16b3330442537211,5609987844990570937_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.010000+00:00,43,0,100,"[0, 100]",[5]
44,60d1a82016b3330442537244,60d1a81f16b3330442537211,5646870611503620553_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.011000+00:00,44,0,100,"[0, 100]",[2]
45,60d1a82016b3330442537245,60d1a81f16b3330442537211,5678313728368360859_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.011000+00:00,45,0,100,"[0, 100]",[2]
46,60d1a82016b3330442537246,60d1a81f16b3330442537211,5740071104871774323_0,False,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_B,0,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.012000+00:00,46,0,100,"[0, 100]",[1]
47,60d1a82016b3330442537222,60d1a81f16b3330442537211,5438574239652778058_1,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_A,1,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,47,0,100,"[0, 100]","[6, 7, 1, 4, 2, 3]"
48,60d1a82016b3330442537223,60d1a81f16b3330442537211,5438574239652778058_2,True,2021-06-22 00:00:00+07:00,2021-09-30 00:00:00+07:00,CLASS_A,1,2589743.50,[5181053909251379448],{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.997000+00:00,48,0,100,"[0, 100]",[7]
49,60d1a82016b3330442537226,60d1a81f16b3330442537211,4638036435127515710_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,0,4120000.00,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.998000+00:00,49,0,66,"[0, 66]",[1]
50,60d1a82016b333044253722c,60d1a81f16b3330442537211,4818379653085429819_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,0,140000.00,[4827998237552142792],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.001000+00:00,50,0,66,"[0, 66]",[0]
51,60d1a82016b3330442537230,60d1a81f16b3330442537211,4943071185361192679_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,0,4240000.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.002000+00:00,51,0,66,"[0, 66]",[5]
52,60d1a82016b333044253723a,60d1a81f16b3330442537211,5152950634416065152_0,False,2021-06-22 00:00:00+07:00,2021-08-27 00:00:00+07:00,CLASS_A,0,4180000.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.007000+00:00,52,0,66,"[0, 66]",[2]

Bỏ các cột không cần thiết:

In [36]:
to_drop = ['_id', 'startDate', 'expiredDate','startInt','expiredInt']
df_campaigns.drop(columns =to_drop, inplace = True, errors='ignore')
df_campaigns

,problemId,original_id,isNetwork,priority,type,total,place_ids,weights,profiles,createDate,solve_id,dates,solve_place_ids
0,60d1a81f16b3330442537211,4768939651732014836_1,True,CLASS_B,1,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.991000+00:00,0,"[0, 100]","[6, 7, 1, 4, 2, 3]"
1,60d1a81f16b3330442537211,4768939651732014836_2,True,CLASS_B,1,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.992000+00:00,1,"[0, 100]",[7]
2,60d1a81f16b3330442537211,4810238136557669178_1,True,CLASS_B,1,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.992000+00:00,2,"[0, 100]","[6, 7, 1, 4, 2, 3]"
3,60d1a81f16b3330442537211,4810238136557669178_2,True,CLASS_B,1,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.992000+00:00,3,"[0, 100]",[7]
4,60d1a81f16b3330442537211,5247609002361599862_1,True,CLASS_B,1,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.993000+00:00,4,"[0, 100]","[6, 7, 1, 4, 2, 3]"
5,60d1a81f16b3330442537211,5247609002361599862_2,True,CLASS_B,1,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.993000+00:00,5,"[0, 100]",[7]
6,60d1a81f16b3330442537211,5275363820481263653_1,True,CLASS_B,1,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.993000+00:00,6,"[0, 100]","[6, 7, 1, 4, 2, 3]"
7,60d1a81f16b3330442537211,5275363820481263653_2,True,CLASS_B,1,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.994000+00:00,7,"[0, 100]",[7]
8,60d1a81f16b3330442537211,5322575190744422716_1,True,CLASS_B,1,166924.75,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.994000+00:00,8,"[0, 100]","[6, 7, 1, 4, 2, 3]"
9,60d1a81f16b3330442537211,5322575190744422716_2,True,CLASS_B,1,19235.00,[5181053909251379448],{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.994000+00:00,9,"[0, 100]",[7]
10,60d1a81f16b3330442537211,5370791925364426073_1,True,CLASS_B,1,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.995000+00:00,10,"[0, 100]","[6, 7, 1, 4, 2, 3]"
11,60d1a81f16b3330442537211,5370791925364426073_2,True,CLASS_B,1,2589743.50,[5181053909251379448],{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.995000+00:00,11,"[0, 100]",[7]
12,60d1a81f16b3330442537211,5387657435205013825_1,True,CLASS_B,1,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.995000+00:00,12,"[0, 100]","[6, 7, 1, 4, 2, 3]"
13,60d1a81f16b3330442537211,5387657435205013825_2,True,CLASS_B,1,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,13,"[0, 100]",[7]
14,60d1a81f16b3330442537211,5400965728863573515_1,True,CLASS_B,1,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,14,"[0, 100]","[6, 7, 1, 4, 2, 3]"
15,60d1a81f16b3330442537211,5400965728863573515_2,True,CLASS_B,1,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,15,"[0, 100]",[7]
16,60d1a81f16b3330442537211,5577398347147938092_1,True,CLASS_B,1,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.997000+00:00,16,"[0, 100]","[6, 7, 1, 4, 2, 3]"
17,60d1a81f16b3330442537211,5577398347147938092_2,True,CLASS_B,1,2589743.50,[5181053909251379448],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.997000+00:00,17,"[0, 100]",[7]
18,60d1a81f16b3330442537211,4650504253994331355_0,False,CLASS_B,0,2589239.00,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.998000+00:00,18,"[0, 66]",[1]
19,60d1a81f16b3330442537211,4713760987931352697_0,False,CLASS_B,0,4240000.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.998000+00:00,19,"[0, 66]",[5]
20,60d1a81f16b3330442537211,4718198705721931407_0,False,CLASS_B,0,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.999000+00:00,20,"[0, 100]",[5]
21,60d1a81f16b3330442537211,4741325520555630568_0,False,CLASS_B,0,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40+00:00,21,"[0, 100]",[2]
22,60d1a81f16b3330442537211,4796633772157943273_0,False,CLASS_B,0,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.001000+00:00,22,"[0, 100]",[2]
23,60d1a81f16b3330442537211,4823653667180754890_0,False,CLASS_B,0,1229684.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.001000+00:00,23,"[0, 66]",[2]
24,60d1a81f16b3330442537211,4824859557802329616_0,False,CLASS_B,0,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.002000+00:00,24,"[0, 100]",[1]
25,60d1a81f16b3330442537211,4904151939315150524_0,False,CLASS_B,0,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.002000+00:00,25,"[0, 100]",[1]
26,60d1a81f16b3330442537211,4987628296907052401_0,False,CLASS_B,0,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.003000+00:00,26,"[0, 100]",[5]
27,60d1a81f16b3330442537211,5004060173322688003_0,False,CLASS_B,0,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.003000+00:00,27,"[0, 100]",[5]
28,60d1a81f16b3330442537211,5005141348821177586_0,False,CLASS_B,0,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.004000+00:00,28,"[0, 100]",[2]
29,60d1a81f16b3330442537211,5008562159266208975_0,False,CLASS_B,0,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.004000+00:00,29,"[0, 100]",[1]
30,60d1a81f16b3330442537211,5112510634931261580_0,False,CLASS_B,0,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.005000+00:00,30,"[0, 100]",[1]
31,60d1a81f16b3330442537211,5116176280026807920_0,False,CLASS_B,0,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.005000+00:00,31,"[0, 100]",[1]
32,60d1a81f16b3330442537211,5140955443670820219_0,False,CLASS_B,0,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.005000+00:00,32,"[0, 100]",[2]
33,60d1a81f16b3330442537211,5144070500760291817_0,False,CLASS_B,0,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.006000+00:00,33,"[0, 100]",[5]
34,60d1a81f16b3330442537211,5145360317263062170_0,False,CLASS_B,0,163588.39,[4827998237552142792],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.006000+00:00,34,"[0, 66]",[0]
35,60d1a81f16b3330442537211,5261690011954745524_0,False,CLASS_B,0,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.007000+00:00,35,"[0, 100]",[5]
36,60d1a81f16b3330442537211,5326884055688590955_0,False,CLASS_B,0,1118869.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.007000+00:00,36,"[0, 66]",[5]
37,60d1a81f16b3330442537211,5349652368050952557_0,False,CLASS_B,0,4120000.00,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.008000+00:00,37,"[0, 66]",[1]
38,60d1a81f16b3330442537211,5351581853241914431_0,False,CLASS_B,0,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.008000+00:00,38,"[0, 100]",[1]
39,60d1a81f16b3330442537211,5430288141589897773_0,False,CLASS_B,0,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.008000+00:00,39,"[0, 100]",[2]
40,60d1a81f16b3330442537211,5447298725065630394_0,False,CLASS_B,0,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.009000+00:00,40,"[0, 100]",[5]
41,60d1a81f16b3330442537211,5471706532034127453_0,False,CLASS_B,0,4180000.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.009000+00:00,41,"[0, 66]",[2]
42,60d1a81f16b3330442537211,5596899021949443719_0,False,CLASS_B,0,140000.00,[4827998237552142792],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.010000+00:00,42,"[0, 66]",[0]
43,60d1a81f16b3330442537211,5609987844990570937_0,False,CLASS_B,0,3660171.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.010000+00:00,43,"[0, 100]",[5]
44,60d1a81f16b3330442537211,5646870611503620553_0,False,CLASS_B,0,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.011000+00:00,44,"[0, 100]",[2]
45,60d1a81f16b3330442537211,5678313728368360859_0,False,CLASS_B,0,3608376.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.011000+00:00,45,"[0, 100]",[2]
46,60d1a81f16b3330442537211,5740071104871774323_0,False,CLASS_B,0,3556581.20,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.012000+00:00,46,"[0, 100]",[1]
47,60d1a81f16b3330442537211,5438574239652778058_1,True,CLASS_A,1,103632.91,"[4979871131880682040, 5181053909251379448, 485...",{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.996000+00:00,47,"[0, 100]","[6, 7, 1, 4, 2, 3]"
48,60d1a81f16b3330442537211,5438574239652778058_2,True,CLASS_A,1,2589743.50,[5181053909251379448],{'-140': 20.0},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.997000+00:00,48,"[0, 100]",[7]
49,60d1a81f16b3330442537211,4638036435127515710_0,False,CLASS_A,0,4120000.00,[4857469430519615278],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:39.998000+00:00,49,"[0, 66]",[1]
50,60d1a81f16b3330442537211,4818379653085429819_0,False,CLASS_A,0,140000.00,[4827998237552142792],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.001000+00:00,50,"[0, 66]",[0]
51,60d1a81f16b3330442537211,4943071185361192679_0,False,CLASS_A,0,4240000.00,[5023173597424371233],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.002000+00:00,51,"[0, 66]",[5]
52,60d1a81f16b3330442537211,5152950634416065152_0,False,CLASS_A,0,4180000.00,[5538742900884010760],{},<solver_helpers.CampaignProfile object at 0x00...,2021-06-22 09:06:40.007000+00:00,52,"[0, 66]",[2]

DataFrame ở trên chính là `preprocessed_data.campaigns`<br>
Cuối cùng 2 hàm dưới để tạo ra 1 campaign_mapper

In [37]:
campaigns_mapper = pd.DataFrame({'original_id' : df_campaigns['original_id'].to_list(), 'solve_id' : df_campaigns['solve_id'].to_list()})
campaigns_mapper_solve_to_original_dict = {solve : original for solve, original in  zip(df_campaigns['solve_id'],df_campaigns['original_id'])}
print(f'Campaign Mapper: {campaigns_mapper_solve_to_original_dict}')

Campaign Mapper: {0: '4768939651732014836_1', 1: '4768939651732014836_2', 2: '4810238136557669178_1', 3: '4810238136557669178_2', 4: '5247609002361599862_1', 5: '5247609002361599862_2', 6: '5275363820481263653_1', 7: '5275363820481263653_2', 8: '5322575190744422716_1', 9: '5322575190744422716_2', 10: '5370791925364426073_1', 11: '5370791925364426073_2', 12: '5387657435205013825_1', 13: '5387657435205013825_2', 14: '5400965728863573515_1', 15: '5400965728863573515_2', 16: '5577398347147938092_1', 17: '5577398347147938092_2', 18: '4650504253994331355_0', 19: '4713760987931352697_0', 20: '4718198705721931407_0', 21: '4741325520555630568_0', 22: '4796633772157943273_0', 23: '4823653667180754890_0', 24: '4824859557802329616_0', 25: '4904151939315150524_0', 26: '4987628296907052401_0', 27: '5004060173322688003_0', 28: '5005141348821177586_0', 29: '5008562159266208975_0', 30: '5112510634931261580_0', 31: '5116176280026807920_0', 32: '5140955443670820219_0', 33: '5144070500760291817_0', 34: '5145360317263062170_0', 35: '5261690011954745524_0', 36: '5326884055688590955_0', 37: '5349652368050952557_0', 38: '5351581853241914431_0', 39: '5430288141589897773_0', 40: '5447298725065630394_0', 41: '5471706532034127453_0', 42: '5596899021949443719_0', 43: '5609987844990570937_0', 44: '5646870611503620553_0', 45: '5678313728368360859_0', 46: '5740071104871774323_0', 47: '5438574239652778058_1', 48: '5438574239652778058_2', 49: '4638036435127515710_0', 50: '4818379653085429819_0', 51: '4943071185361192679_0', 52: '5152950634416065152_0'}

## IV. Phụ lục

### 4.1 PlaceProfile và CampaignProfile

PlaceProfile và CampaignProfile đều có 3 attribute: `db_rep`, `list_rep` và `int_rep`

#### a. PlaceProfile

Xét 1 địa điểm có `db_rep` như dưới

In [38]:
place_db_rep = [{'type': 'AGE',
  'ratio': [0.0023422095,
   0.04535171,
   0.06319563,
   0.045249052,
   0.024730375,
   0.014243808,
   0.025496023,
   0.77939117]},
 {'ratio': [0.118145056, 0.10246408, 0.7793909], 'type': 'GENDER'}]

Điều này có nghĩa là tại địa điểm này, tỉ lệ người nhóm tuổi 0 là 0.0023422095, nhớm tuổi 3 là 0.045249052,... tỉ lệ giới tính 0 (nữ?) là 0.118145056, 1 là 0.10246408.<br> Ta khởi tạo một đối tượng `PlaceProfile` từ db rep này:

In [39]:
p_profile = PlaceProfile(place_db_rep)
p_list_rep = p_profile.list_rep
p_int_rep = p_profile.int_rep
print(f"List rep {p_list_rep}")
print(f"Int rep {p_profile.int_rep}")

List rep [[0.118145056, 0.10246408, 0.7793909], [0.0023422095, 0.04535171, 0.06319563, 0.045249052, 0.024730375, 0.014243808, 0.025496023, 0.77939117]]
Int rep [0.000276720472541232, 0.005358080317645761, 0.007466251245305281, 0.005345951782486912, 0.002921771539276, 0.001682835493813248, 0.003012229065112288, 0.09208121342555552, 0.00023999234158476003, 0.0046469212415768, 0.0064752820879704, 0.00463640248405216, 0.0025339751224299997, 0.00145947868241664, 0.00261242654035384, 0.0798595991941736, 0.0018254967701935502, 0.035346710073439, 0.049254098941767, 0.035266699362426795, 0.019274629228587498, 0.0111014943365472, 0.0198713683123907, 0.6074503854383531]

List rep thì khá dễ hiểu, nó là 2  list chứa các giá trị tương ứng lần lượt với gender và age.<br>
Còn về int rep: `p_int_rep[0]` chính là tỉ lệ người giới tính 0 và nhóm tuổi 0 đến place đấy, `p_int_rep[1]` là tỉ lệ giới tính 0 và nhóm tuổi 1 , `p_int_rep[5]` là giới tính 0 và độ tuổi 5, `p_int_rep[14]` là giới tính 1 và nhóm tuổi 6...

#### b. CampaignProfile

CampaignProfile cũng tương tự:

Xét 1 campaign có profile như dưới

In [40]:
c_db_rep = [[{'values': [0], 'type': 'GENDER'}, {'type': 'AGE', 'values': [0, 1, 2]}],
            [{'values': [1], 'type': 'GENDER'}, {'type': 'AGE', 'values': [4,5]}]]

campaign này yêu cầu đối tượng giới tính 0 __và__ nhóm tuổi [0,1,2] __hoặc__ giới tính 1 __và__ độ tuổi [4,5].<br>
Ta khởi tạo 1 đối tượng  CampaignProfile từ db rep này:

In [41]:
c_profile = CampaignProfile(c_db_rep)
c_list_rep = c_profile.list_rep
c_int_rep = c_profile.int_rep
print(f"List rep: {c_list_rep}")
print(f"Int rep: {c_profile.int_rep}")

List rep: [[0, 0], [0, 1], [0, 2], [1, 4], [1, 5]]
Int rep: frozenset({0, 1, 2, 12, 13})